<?php
$AIRLINESORIGINAL = 
[
['name' => ' - Jet Airways', 'code' => '', 'quality' => 1.10, 'hubs' => ['BOM', 'DEL']],
['name' => '0B - Blue Air', 'code' => '0B', 'quality' => 1.05, 'hubs' => ['OTP']],
['name' => '11 - Gambia Experience Airlines', 'code' => '11', 'quality' => 1.05, 'hubs' => ['BJL']],
['name' => '2B - ATA Aerocondor', 'code' => '2B', 'quality' => 1.10, 'hubs' => ['LIS']],
['name' => '2D - AEROVIP', 'code' => '2D', 'quality' => 1.00, 'hubs' => ['MAD']],
['name' => '2F - Payam Air Center Service', 'code' => '2F', 'quality' => 1.05, 'hubs' => ['THR']],
['name' => '2G - NORTHWEST SEAPLANES', 'code' => '2G', 'quality' => 1.00, 'hubs' => ['SEA']],
['name' => '2J - Air Burkina', 'code' => '2J', 'quality' => 1.05, 'hubs' => ['OUA']],
['name' => '2K - Avianca Ecuador', 'code' => '2K', 'quality' => 1.10, 'hubs' => ['UIO', 'GYE']],
['name' => '2L - Odette Airways', 'code' => '2L', 'quality' => 1.00, 'hubs' => ['CDG']],
['name' => '2M - Moldavian Airlines', 'code' => '2M', 'quality' => 1.05, 'hubs' => ['KIV']],
['name' => '2N - Yuzmashavia', 'code' => '2N', 'quality' => 1.00, 'hubs' => ['UFA']],
['name' => '2P - Air Philippines', 'code' => '2P', 'quality' => 1.05, 'hubs' => ['MNL']],
['name' => '2Q - Air Cargo Carriers', 'code' => '2Q', 'quality' => 1.00, 'hubs' => ['MKE']],
['name' => '2S - Island Express', 'code' => '2S', 'quality' => 1.05, 'hubs' => ['HNL']],
['name' => '2T - Canada 3000', 'code' => '2T', 'quality' => 1.10, 'hubs' => ['YYZ']],
['name' => '2U - ATLAS INTERNATIONAL', 'code' => '2U', 'quality' => 1.00, 'hubs' => ['IST']],
['name' => '2W - WELCOME AIR', 'code' => '2W', 'quality' => 1.05, 'hubs' => ['VIE']],
['name' => '2Y - AIR ANDAMAN', 'code' => '2Y', 'quality' => 1.00, 'hubs' => ['BKK']],
['name' => '2Z - Changan Airlines', 'code' => '2Z', 'quality' => 1.10, 'hubs' => ['XIY']],
['name' => '3C - Corporate Airlines', 'code' => '3C', 'quality' => 1.00, 'hubs' => ['STL']],
['name' => '3D - Denim Air', 'code' => '3D', 'quality' => 1.05, 'hubs' => ['AMS']],
['name' => '3G - Gambia Bird', 'code' => '3G', 'quality' => 1.00, 'hubs' => ['BJL']],
['name' => '3H - Air Inuit', 'code' => '3H', 'quality' => 1.05, 'hubs' => ['YFB']],
['name' => '3J - ZIP AIR', 'code' => '3J', 'quality' => 1.00, 'hubs' => ['NRT']],
['name' => '3K - Jetstar Asia Airways', 'code' => '3K', 'quality' => 1.05, 'hubs' => ['SIN']],
['name' => '3L - Intersky', 'code' => '3L', 'quality' => 1.00, 'hubs' => ['FRA']],
['name' => '3M - Gulfstream International Airlines', 'code' => '3M', 'quality' => 1.05, 'hubs' => ['FLL']],
['name' => '3N - Air Urga', 'code' => '3N', 'quality' => 1.00, 'hubs' => ['KBP']],
['name' => '3P - INTER TROPICAL AVIATION', 'code' => '3P', 'quality' => 1.05, 'hubs' => ['PAP']],
['name' => '3Q - China Yunnan Airlines', 'code' => '3Q', 'quality' => 1.10, 'hubs' => ['KMG']],
['name' => '3R - Avia Air', 'code' => '3R', 'quality' => 1.00, 'hubs' => ['LED']],
['name' => '3S - Tashkent Aircraft Production Corporation', 'code' => '3S', 'quality' => 1.05, 'hubs' => ['TAS']],
['name' => '3T - TURAN AIR', 'code' => '3T', 'quality' => 1.00, 'hubs' => ['GYD']],
['name' => '3U - Sichuan Airlines', 'code' => '3U', 'quality' => 1.10, 'hubs' => ['CTU']],
['name' => '3V - TNT AIRWAYS', 'code' => '3V', 'quality' => 1.05, 'hubs' => ['LGG']],
['name' => '3W - Nanjing Airlines', 'code' => '3W', 'quality' => 1.00, 'hubs' => ['NKG']],
['name' => '3X - Japan Air Commuter', 'code' => '3X', 'quality' => 1.05, 'hubs' => ['FUK']],
['name' => '3Z - Necon Air', 'code' => '3Z', 'quality' => 1.00, 'hubs' => ['KTM']],
['name' => '4A - FS AIR SERVICE', 'code' => '4A', 'quality' => 1.25, 'hubs' => ['CAI']],
['name' => '4C - LATAM Airlines Colombia', 'code' => '4C', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => '4D - Air Sinai', 'code' => '4D', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => '4G - Gazpromavia', 'code' => '4G', 'quality' => 1.05, 'hubs' => ['LAX']],
['name' => '4H - Fly Linhas Aereas', 'code' => '4H', 'quality' => 1.3, 'hubs' => ['SCL']],
['name' => '4K - Kenn Borek Air', 'code' => '4K', 'quality' => 1.25, 'hubs' => ['CMN']],
['name' => '4L - AIR ASTANA', 'code' => '4L', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => '4M - LATAM Airlines Argentina', 'code' => '4M', 'quality' => 1.05, 'hubs' => ['BCN']],
['name' => '4N - Air North Charter', 'code' => '4N', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => '4O - Interjet', 'code' => '4O', 'quality' => 1.25, 'hubs' => ['UIO']],
['name' => '4Q - AeroLyon', 'code' => '4Q', 'quality' => 1.35, 'hubs' => ['MAD']],
['name' => '4R - HAMBURG INTERNATIONAL', 'code' => '4R', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => '4T - BELAIR AIRLINES [SWITZERLAND]', 'code' => '4T', 'quality' => 1.25, 'hubs' => ['ADD']],
['name' => '4U - Germanwings', 'code' => '4U', 'quality' => 1.35, 'hubs' => ['MEX']],
['name' => '4V - Voyageur Airways', 'code' => '4V', 'quality' => 1.1, 'hubs' => ['BOG']],
['name' => '4W - Allied Air', 'code' => '4W', 'quality' => 1, 'hubs' => ['JFK']],
['name' => '4Y - Yute Air Alaska', 'code' => '4Y', 'quality' => 1.25, 'hubs' => ['KUL']],
['name' => '4Z - Airlink', 'code' => '4Z', 'quality' => 1.1, 'hubs' => ['DEN']],
['name' => '5A - ALPINE AIR CHILE', 'code' => '5A', 'quality' => 1.1, 'hubs' => ['AKL']],
['name' => '5B - EURO-ASIA AIR', 'code' => '5B', 'quality' => 1.25, 'hubs' => ['CMN']],
['name' => '5C - CAL Cargo Airlines', 'code' => '5C', 'quality' => 1.1, 'hubs' => ['ZUR']],
['name' => '5D - V BIRD AIRLINES', 'code' => '5D', 'quality' => 1, 'hubs' => ['CDG']],
['name' => '5E - EQUAFLIGHT SERVICE', 'code' => '5E', 'quality' => 1.1, 'hubs' => ['ICN']],
['name' => '5F - Arctic Circle Air Service', 'code' => '5F', 'quality' => 1.3, 'hubs' => ['MEX']],
['name' => '5G - Skyservice', 'code' => '5G', 'quality' => 1.35, 'hubs' => ['LHR']],
['name' => '5H - Five Fourty Aviation ', 'code' => '5H', 'quality' => 1.35, 'hubs' => ['YYZ']],
['name' => '5J - Cebu Pacific Air', 'code' => '5J', 'quality' => 1.05, 'hubs' => ['MNL']],
['name' => '5K - Hi Fly', 'code' => '5K', 'quality' => 1.25, 'hubs' => ['KUL']],
['name' => '5L - Aerosur', 'code' => '5L', 'quality' => 1.25, 'hubs' => ['LAX']],
['name' => '5M - Sibaviatrans', 'code' => '5M', 'quality' => 1.3, 'hubs' => ['MEX']],
['name' => '5N - Nordavia Regional Airlines', 'code' => '5N', 'quality' => 1, 'hubs' => ['ATL']],
['name' => '5P - PENTA', 'code' => '5P', 'quality' => 1.25, 'hubs' => ['NAN']],
['name' => '5R - IRS AERO', 'code' => '5R', 'quality' => 1, 'hubs' => ['CGK']],
['name' => '5S - L\'Aeropostale', 'code' => '5S', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => '5T - Canadian North', 'code' => '5T', 'quality' => 1, 'hubs' => ['HKG']],
['name' => '5U - LADE - Lineas Aereas Del Estado', 'code' => '5U', 'quality' => 1.25, 'hubs' => ['HNL']],
['name' => '5V - Lvov Airlines', 'code' => '5V', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => '5W - United Air Express', 'code' => '5W', 'quality' => 1.05, 'hubs' => ['BKK']],
['name' => '5X - UPS Airlines', 'code' => '5X', 'quality' => 1.05, 'hubs' => ['FRA']],
['name' => '5Y - Atlas Air', 'code' => '5Y', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => '5Z - BISMILLAH AIRLINES', 'code' => '5Z', 'quality' => 1, 'hubs' => ['NAN']],
['name' => '6A - Aviacsa', 'code' => '6A', 'quality' => 1.25, 'hubs' => ['MXP']],
['name' => '6B - Brittania Airways Sweden', 'code' => '6B', 'quality' => 1.3, 'hubs' => ['CDG']],
['name' => '6C - Cape Smythe Air Service', 'code' => '6C', 'quality' => 1.3, 'hubs' => ['BAH']],
['name' => '6E - CITY-AIR [GERMANY]', 'code' => '6E', 'quality' => 1.1, 'hubs' => ['LHR']],
['name' => '6F - Laker Airways', 'code' => '6F', 'quality' => 1.3, 'hubs' => ['ADD']],
['name' => '6G - AIR WALES', 'code' => '6G', 'quality' => 1.1, 'hubs' => ['NAN']],
['name' => '6H - Israir', 'code' => '6H', 'quality' => 1, 'hubs' => ['ZUR']],
['name' => '6J - SKYNET ASIA AIRWAYS', 'code' => '6J', 'quality' => 1.1, 'hubs' => ['HNL']],
['name' => '6K - Asian Spirit', 'code' => '6K', 'quality' => 1.25, 'hubs' => ['DOH']],
['name' => '6L - Aklak Air', 'code' => '6L', 'quality' => 1.35, 'hubs' => ['CAI']],
['name' => '6N - Aerosucre', 'code' => '6N', 'quality' => 1.25, 'hubs' => ['FCO']],
['name' => '6Q - Slovak Airlines - Slovenske Aerolinie', 'code' => '6Q', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => '6R - AEROTRANSPORTE DE CARGA UNION', 'code' => '6R', 'quality' => 1.25, 'hubs' => ['HNL']],
['name' => '6S - SaudiGulf Airlines', 'code' => '6S', 'quality' => 1.05, 'hubs' => ['ORD']],
['name' => '6T - ALMATY AVIA', 'code' => '6T', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => '6U - AIR UKRAINE', 'code' => '6U', 'quality' => 1.3, 'hubs' => ['TLV']],
['name' => '6V - Air Vegas', 'code' => '6V', 'quality' => 1, 'hubs' => ['ICN']],
['name' => '6X - Belgium Air Force', 'code' => '6X', 'quality' => 1.1, 'hubs' => ['LHR']],
['name' => '6Y - NICA - Nicaraguenses de Aviacion', 'code' => '6Y', 'quality' => 1.3, 'hubs' => ['JFK']],
['name' => '6Z - PANAVIA', 'code' => '6Z', 'quality' => 1.05, 'hubs' => ['HKG']],
['name' => '7B - KRASNOYARSK AIRLINES', 'code' => '7B', 'quality' => 1.3, 'hubs' => ['FRA']],
['name' => '7C - Jeju Air', 'code' => '7C', 'quality' => 1.3, 'hubs' => ['MEL']],
['name' => '7D - Donbass Eastern Ukranian Airlines', 'code' => '7D', 'quality' => 1.35, 'hubs' => ['HNL']],
['name' => '7E - Panagra Airways', 'code' => '7E', 'quality' => 1.35, 'hubs' => ['CAI']],
['name' => '7F - First Air', 'code' => '7F', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => '7G - MK Airlines', 'code' => '7G', 'quality' => 1.35, 'hubs' => ['JED']],
['name' => '7H - Ravn Alaska', 'code' => '7H', 'quality' => 1.3, 'hubs' => ['BOG']],
['name' => '7I - IMPERIAL AIR', 'code' => '7I', 'quality' => 1.35, 'hubs' => ['CDG']],
['name' => '7J - SKAGWAY AIR SERVICE INC.', 'code' => '7J', 'quality' => 1.25, 'hubs' => ['JFK']],
['name' => '7K - Kogalymavia', 'code' => '7K', 'quality' => 1.35, 'hubs' => ['NRT']],
['name' => '7L - Silk Way West Airlines', 'code' => '7L', 'quality' => 1.1, 'hubs' => ['JNB']],
['name' => '7M - Tyumen Airlines', 'code' => '7M', 'quality' => 1.1, 'hubs' => ['LIM']],
['name' => '7N - AIR MANITOBA', 'code' => '7N', 'quality' => 1.3, 'hubs' => ['NAN']],
['name' => '7P - BATAVIA AIR', 'code' => '7P', 'quality' => 1.1, 'hubs' => ['IST']],
['name' => '7Q - Shorouk Air', 'code' => '7Q', 'quality' => 1, 'hubs' => ['BCN']],
['name' => '7R - RED SEA AIR', 'code' => '7R', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => '7S - ARCTIC TRANSPORTATION SERVICES INC.', 'code' => '7S', 'quality' => 1.1, 'hubs' => ['LHR']],
['name' => '7T - Trans Am', 'code' => '7T', 'quality' => 1.25, 'hubs' => ['NRT']],
['name' => '7U - Aviaenergo', 'code' => '7U', 'quality' => 1.3, 'hubs' => ['HKG']],
['name' => '7V - PELICAN AIR SERVICES', 'code' => '7V', 'quality' => 1, 'hubs' => ['SEA']],
['name' => '7W - AVIATION ASSISTANCE A/S', 'code' => '7W', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => '7X - TNT International Aviation', 'code' => '7X', 'quality' => 1.25, 'hubs' => ['KUL']],
['name' => '7Z - LAKER AIRWAYS BAHAMAS', 'code' => '7Z', 'quality' => 1.3, 'hubs' => ['LAS']],
['name' => '8B - Baker Aviation', 'code' => '8B', 'quality' => 1.25, 'hubs' => ['SIN']],
['name' => '8C - Air Transport International - ATI', 'code' => '8C', 'quality' => 1, 'hubs' => ['JNB']],
['name' => '8D - Expo Aviation', 'code' => '8D', 'quality' => 1.35, 'hubs' => ['CAI']],
['name' => '8E - BERING AIR INC.', 'code' => '8E', 'quality' => 1, 'hubs' => ['BAH']],
['name' => '8F - Fischer Air', 'code' => '8F', 'quality' => 1, 'hubs' => ['ICN']],
['name' => '8G - Angel Airlines', 'code' => '8G', 'quality' => 1.05, 'hubs' => ['IST']],
['name' => '8J - Komiinteravia', 'code' => '8J', 'quality' => 1, 'hubs' => ['ZUR']],
['name' => '8L - Lucky Air', 'code' => '8L', 'quality' => 1.25, 'hubs' => ['JFK']],
['name' => '8M - Myanmar Airways International', 'code' => '8M', 'quality' => 1.35, 'hubs' => ['CMN']],
['name' => '8N - NORDKALOTTFLYG AB', 'code' => '8N', 'quality' => 1.1, 'hubs' => ['DOH']],
['name' => '8P - PACIFIC COASTAL AIRLINES', 'code' => '8P', 'quality' => 1.05, 'hubs' => ['ICN']],
['name' => '8Q - Onur Air', 'code' => '8Q', 'quality' => 1.35, 'hubs' => ['UIO']],
['name' => '8S - SAAK - Stavropol Avia', 'code' => '8S', 'quality' => 1.05, 'hubs' => ['CMN']],
['name' => '8U - Afriqiyah Airways', 'code' => '8U', 'quality' => 1, 'hubs' => ['DXB']],
['name' => '8Y - Air Burundi', 'code' => '8Y', 'quality' => 1.3, 'hubs' => ['AKL']],
['name' => '8Z - Congo Airways', 'code' => '8Z', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => '9B - AccesRail', 'code' => '9B', 'quality' => 1, 'hubs' => ['ORD']],
['name' => '9C - Gill Airways', 'code' => '9C', 'quality' => 1.05, 'hubs' => ['DXB']],
['name' => '9D - Perm State Air Enterprise', 'code' => '9D', 'quality' => 1.3, 'hubs' => ['AKL']],
['name' => '9E - Pinnacle Airlines', 'code' => '9E', 'quality' => 1.1, 'hubs' => ['ORD']],
['name' => '9F - HAITI AIR FREIGHT', 'code' => '9F', 'quality' => 1.35, 'hubs' => ['SEA']],
['name' => '9G - UKRAINE AIRSERVICE AIRLINES', 'code' => '9G', 'quality' => 1.05, 'hubs' => ['SCL']],
['name' => '9H - Bonair Exel', 'code' => '9H', 'quality' => 1.1, 'hubs' => ['GRU']],
['name' => '9J - Pacific Island Aviation', 'code' => '9J', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => '9K - Capital Airlines', 'code' => '9K', 'quality' => 1.1, 'hubs' => ['MEL']],
['name' => '9L - Colgan Air', 'code' => '9L', 'quality' => 1.25, 'hubs' => ['ATL']],
['name' => '9N - ANA and Japan Post Express', 'code' => '9N', 'quality' => 1.25, 'hubs' => ['SIN']],
['name' => '9P - PELANGI AIR', 'code' => '9P', 'quality' => 1.05, 'hubs' => ['FCO']],
['name' => '9Q - PB Air', 'code' => '9Q', 'quality' => 1.25, 'hubs' => ['NAN']],
['name' => '9R - PHUKET AIRLINES', 'code' => '9R', 'quality' => 1.1, 'hubs' => ['MIA']],
['name' => '9S - SOUTHERN AIR [CT-USA]', 'code' => '9S', 'quality' => 1.3, 'hubs' => ['LIM']],
['name' => '9T - Athabaska Airways', 'code' => '9T', 'quality' => 1.25, 'hubs' => ['IST']],
['name' => '9U - Air Moldova', 'code' => '9U', 'quality' => 1.35, 'hubs' => ['JED']],
['name' => '9V - AVIONES DE ORIENTE', 'code' => '9V', 'quality' => 1, 'hubs' => ['LAG']],
['name' => '9W - Jet Airways', 'code' => '9W', 'quality' => 1.05, 'hubs' => ['HKG']],
['name' => '9X - TRASPORTI AEREI ITALIANI', 'code' => '9X', 'quality' => 1.05, 'hubs' => ['IST']],
['name' => '9Y - Air Kazakstan', 'code' => '9Y', 'quality' => 1, 'hubs' => ['MAD']],
['name' => 'A2 - CIELOS DEL PERU', 'code' => 'A2', 'quality' => 1.05, 'hubs' => ['CAI']],
['name' => 'A3 - Aegean Aviation', 'code' => 'A3', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => 'A4 - Southern Winds', 'code' => 'A4', 'quality' => 1.25, 'hubs' => ['RUH']],
['name' => 'A5 - AIRLINAIR', 'code' => 'A5', 'quality' => 1.1, 'hubs' => ['NRT']],
['name' => 'A6 - AIR ALPS AVIATION', 'code' => 'A6', 'quality' => 1.1, 'hubs' => ['MEX']],
['name' => 'A7 - Air Plus Comet', 'code' => 'A7', 'quality' => 1.25, 'hubs' => ['FRA']],
['name' => 'A8 - AMUR AVIAKOMPANIA', 'code' => 'A8', 'quality' => 1.1, 'hubs' => ['MIA']],
['name' => 'A9 - Georgian Airways', 'code' => 'A9', 'quality' => 1.25, 'hubs' => ['DOH']],
['name' => 'AA - American Airlines', 'code' => 'AA', 'quality' => 1.30, 'hubs' => ['DFW', 'CLT', 'ORD', 'LAX', 'PHX', 'MIA']],
['name' => 'AB - Air Berlin', 'code' => 'AB', 'quality' => 1.10, 'hubs' => ['TXL', 'DUS']],
['name' => 'AC - Air Canada', 'code' => 'AC', 'quality' => 1.30, 'hubs' => ['YYZ', 'YVR', 'YUL']],
['name' => 'AD - Air Paradise', 'code' => 'AD', 'quality' => 1.35, 'hubs' => ['AKL']],
['name' => 'AE - Mandarin Airlines', 'code' => 'AE', 'quality' => 1, 'hubs' => ['LAX']],
['name' => 'AF - Air France', 'code' => 'AF', 'quality' => 1.35, 'hubs' => ['CDG', 'LYS']],
['name' => 'AG - Air Contractors', 'code' => 'AG', 'quality' => 1.05, 'hubs' => ['ICN']],
['name' => 'AH - Air Algerie', 'code' => 'AH', 'quality' => 1.05, 'hubs' => ['DXB']],
['name' => 'AI - Air India', 'code' => 'AI', 'quality' => 1.10, 'hubs' => ['DEL', 'BOM']],
['name' => 'AJ - Aerocontractors', 'code' => 'AJ', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => 'AK - AirAsia', 'code' => 'AK', 'quality' => 1.05, 'hubs' => ['KUL', 'DMK']],
['name' => 'AL - TransAvia Export', 'code' => 'AL', 'quality' => 1.25, 'hubs' => ['MEX']],
['name' => 'AM - Aeromexico', 'code' => 'AM', 'quality' => 1.10, 'hubs' => ['MEX', 'GDL']],
['name' => 'AN - Ansett Australia', 'code' => 'AN', 'quality' => 1, 'hubs' => ['HNL']],
['name' => 'AO - AUSTRALIAN AIRLINES', 'code' => 'AO', 'quality' => 1.05, 'hubs' => ['SYD']],
['name' => 'AP - Albastar', 'code' => 'AP', 'quality' => 1.05, 'hubs' => ['ORD']],
['name' => 'AQ - Aloha Airlines', 'code' => 'AQ', 'quality' => 1, 'hubs' => ['CMN']],
['name' => 'AR - Aerolineas Argentinas', 'code' => 'AR', 'quality' => 1.10, 'hubs' => ['EZE', 'COR']],
['name' => 'AS - Alaska Airlines', 'code' => 'AS', 'quality' => 1.10, 'hubs' => ['SEA', 'LAX', 'ANC']],
['name' => 'AT - Royal Air Maroc', 'code' => 'AT', 'quality' => 1.10, 'hubs' => ['CMN', 'RBA']],
['name' => 'AU - Austral', 'code' => 'AU', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'AV - Avianca', 'code' => 'AV', 'quality' => 1.10, 'hubs' => ['BOG', 'LIM']],
['name' => 'AW - Africa World Airlines', 'code' => 'AW', 'quality' => 1.35, 'hubs' => ['CMN']],
['name' => 'AX - Trans States Airlines', 'code' => 'AX', 'quality' => 1.25, 'hubs' => ['ZUR']],
['name' => 'AY - Finnair', 'code' => 'AY', 'quality' => 1.10, 'hubs' => ['HEL']],
['name' => 'AZ - Alitalia', 'code' => 'AZ', 'quality' => 1.10, 'hubs' => ['FCO', 'MXP']],
['name' => 'B2 - Belavia Belarusian Airlines', 'code' => 'B2', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'B3 - Bellview Airlines', 'code' => 'B3', 'quality' => 1.35, 'hubs' => ['BAH']],
['name' => 'B4 - Bankair', 'code' => 'B4', 'quality' => 1, 'hubs' => ['AKL']],
['name' => 'B5 - FLIGHTLINE [UK]', 'code' => 'B5', 'quality' => 1.3, 'hubs' => ['AKL']],
['name' => 'B6 - JetBlue', 'code' => 'B6', 'quality' => 1.10, 'hubs' => ['JFK', 'BOS', 'FLL']],
['name' => 'B7 - UNI AIR', 'code' => 'B7', 'quality' => 1.05, 'hubs' => ['VIE']],
['name' => 'B8 - Independence Air', 'code' => 'B8', 'quality' => 1.3, 'hubs' => ['CGK']],
['name' => 'B9 - Iran Airtour Airline', 'code' => 'B9', 'quality' => 1.1, 'hubs' => ['CAI']],
['name' => 'BA - British Airways', 'code' => 'BA', 'quality' => 1.35, 'hubs' => ['LHR', 'LGW']],
['name' => 'BB - SEABORNE AIRLINES', 'code' => 'BB', 'quality' => 1, 'hubs' => ['CGK']],
['name' => 'BC - SKYMARK AIRLINES [JAPAN]', 'code' => 'BC', 'quality' => 1.05, 'hubs' => ['MNL']],
['name' => 'BD - BMI British Midland', 'code' => 'BD', 'quality' => 1, 'hubs' => ['AKL']],
['name' => 'BE - Flybe', 'code' => 'BE', 'quality' => 1.1, 'hubs' => ['LIM']],
['name' => 'BF - BLUEBIRD CARGO', 'code' => 'BF', 'quality' => 1.05, 'hubs' => ['CGK']],
['name' => 'BG - Biman Bangladesh', 'code' => 'BG', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'BI - Royal Brunei', 'code' => 'BI', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => 'BJ - Nouvelair', 'code' => 'BJ', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'BK - Okay Airways', 'code' => 'BK', 'quality' => 1, 'hubs' => ['DXB']],
['name' => 'BL - Jetstar Pacific Airlines', 'code' => 'BL', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'BM - British Midland Airways', 'code' => 'BM', 'quality' => 1.25, 'hubs' => ['GRU']],
['name' => 'BN - Britannia Airways Deutschland', 'code' => 'BN', 'quality' => 1.35, 'hubs' => ['DEN']],
['name' => 'BO - Bouraq Indonesia Airlines', 'code' => 'BO', 'quality' => 1.3, 'hubs' => ['CAI']],
['name' => 'BP - Air Botswana', 'code' => 'BP', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'BQ - Aeromar', 'code' => 'BQ', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => 'BR - Eva Air', 'code' => 'BR', 'quality' => 1.35, 'hubs' => ['MEX']],
['name' => 'BS - British International Helicopters', 'code' => 'BS', 'quality' => 1.1, 'hubs' => ['UIO']],
['name' => 'BT - airBaltic', 'code' => 'BT', 'quality' => 1, 'hubs' => ['DFW']],
['name' => 'BU - Braathens SAFE', 'code' => 'BU', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'BV - Blue Panorama', 'code' => 'BV', 'quality' => 1.1, 'hubs' => ['HNL']],
['name' => 'BW - Caribbean Airlines', 'code' => 'BW', 'quality' => 1.3, 'hubs' => ['JFK']],
['name' => 'BX - COAST AIR [NORWAY]', 'code' => 'BX', 'quality' => 1.1, 'hubs' => ['BKK']],
['name' => 'BY - Britannia Airways', 'code' => 'BY', 'quality' => 1.05, 'hubs' => ['BOM']],
['name' => 'BZ - BLUE DART AVIATION', 'code' => 'BZ', 'quality' => 1, 'hubs' => ['MNL']],
['name' => 'C2 - CHEBOKSARY AIR ENTERPRISE', 'code' => 'C2', 'quality' => 1.35, 'hubs' => ['DXB']],
['name' => 'C3 - Angola Air Charter', 'code' => 'C3', 'quality' => 1, 'hubs' => ['NAN']],
['name' => 'C4 - ZIMEX AVIATION LTD.', 'code' => 'C4', 'quality' => 1.35, 'hubs' => ['DEN']],
['name' => 'C5 - US Airways Express/Commutair', 'code' => 'C5', 'quality' => 1, 'hubs' => ['LIM']],
['name' => 'C6 - CANJET AIRLINES', 'code' => 'C6', 'quality' => 1.35, 'hubs' => ['SEA']],
['name' => 'C7 - RICO LINHAS AEREAS', 'code' => 'C7', 'quality' => 1.1, 'hubs' => ['HKG']],
['name' => 'C8 - Chicago Express Airwasy (ATA Connection)', 'code' => 'C8', 'quality' => 1.3, 'hubs' => ['AUH']],
['name' => 'C9 - Cirrus Air', 'code' => 'C9', 'quality' => 1, 'hubs' => ['UIO']],
['name' => 'CA - Air China', 'code' => 'CA', 'quality' => 1.30, 'hubs' => ['PEK', 'PVG']],
['name' => 'CB - Suckling Airways', 'code' => 'CB', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'CC - Air Atlanta - Atlanta Icelandic Air Transport', 'code' => 'CC', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => 'CD - Alliance Air', 'code' => 'CD', 'quality' => 1.1, 'hubs' => ['MAD']],
['name' => 'CE - Nationwide Airlines', 'code' => 'CE', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'CF - China Postal Airlines', 'code' => 'CF', 'quality' => 1.25, 'hubs' => ['MNL']],
['name' => 'CG - Airlines of Papua New Guinea', 'code' => 'CG', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'CH - Bemidji Airlines', 'code' => 'CH', 'quality' => 1.25, 'hubs' => ['AUH']],
['name' => 'CI - China Airlines', 'code' => 'CI', 'quality' => 1.10, 'hubs' => ['TPE', 'KHH']],
['name' => 'CJ - China Northern Airlines', 'code' => 'CJ', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'CK - China Cargo Airlines', 'code' => 'CK', 'quality' => 1.3, 'hubs' => ['BAH']],
['name' => 'CL - Lufthansa CityLine', 'code' => 'CL', 'quality' => 1.05, 'hubs' => ['MAD']],
['name' => 'CM - Compania Panamena', 'code' => 'CM', 'quality' => 1.10, 'hubs' => ['PTY']],
['name' => 'CO - Continental Airlines', 'code' => 'CO', 'quality' => 1.30, 'hubs' => ['IAH', 'EWR', 'CLE']],
['name' => 'CP - Compass Airlines', 'code' => 'CP', 'quality' => 1.3, 'hubs' => ['MEX']],
['name' => 'CQ - SUNSHINE EXPRESS AIRLINES', 'code' => 'CQ', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'CS - Continental Micronesia', 'code' => 'CS', 'quality' => 1, 'hubs' => ['KUL']],
['name' => 'CT - Air Sofia', 'code' => 'CT', 'quality' => 1.35, 'hubs' => ['HND']],
['name' => 'CU - Cubana', 'code' => 'CU', 'quality' => 1.05, 'hubs' => ['JNB']],
['name' => 'CV - Cargolux', 'code' => 'CV', 'quality' => 1.05, 'hubs' => ['SIN']],
['name' => 'CW - Air Marshall Islands', 'code' => 'CW', 'quality' => 1.25, 'hubs' => ['YVR']],
['name' => 'CX - Cathay Pacific', 'code' => 'CX', 'quality' => 1.35, 'hubs' => ['HKG']],
['name' => 'CY - Cyprus Airways', 'code' => 'CY', 'quality' => 1.35, 'hubs' => ['FCO']],
['name' => 'CZ - China Southern Airlines', 'code' => 'CZ', 'quality' => 1.30, 'hubs' => ['CAN', 'SZX']],
['name' => 'D0 - DHL Air', 'code' => 'D0', 'quality' => 1.1, 'hubs' => ['DFW']],
['name' => 'D2 - SEVERSTAL AIRCOMPANY', 'code' => 'D2', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => 'D3 - Daallo Airlines', 'code' => 'D3', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => 'D5 - NEPC Airlines', 'code' => 'D5', 'quality' => 1.1, 'hubs' => ['RUH']],
['name' => 'D6 - Inter Air Lines', 'code' => 'D6', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => 'D7 - Dinar Lineas Aereas', 'code' => 'D7', 'quality' => 1.1, 'hubs' => ['LAX']],
['name' => 'd8 - Norwegian', 'code' => 'd8', 'quality' => 1.1, 'hubs' => ['ORD']],
['name' => 'd8 - Norwegian', 'code' => 'd8', 'quality' => 1.25, 'hubs' => ['RUH']],
['name' => 'D9 - DON AIRLINES', 'code' => 'D9', 'quality' => 1, 'hubs' => ['DOH']],
['name' => 'DB - Brit Air', 'code' => 'DB', 'quality' => 1.05, 'hubs' => ['BOM']],
['name' => 'DC - GOLDEN AIR FLYG', 'code' => 'DC', 'quality' => 1.35, 'hubs' => ['LAG']],
['name' => 'DE - Condor Flugdienst GmbH', 'code' => 'DE', 'quality' => 1.3, 'hubs' => ['SIN']],
['name' => 'DF - Aerolineas de Baleares', 'code' => 'DF', 'quality' => 1.25, 'hubs' => ['JED']],
['name' => 'DH - Independence Air', 'code' => 'DH', 'quality' => 1.05, 'hubs' => ['YYZ']],
['name' => 'DI - Norwegian Air UK', 'code' => 'DI', 'quality' => 1.05, 'hubs' => ['GRU']],
['name' => 'DJ - VIRGIN BLUE AIRLINES', 'code' => 'DJ', 'quality' => 1, 'hubs' => ['LAX']],
['name' => 'DK - Premiar', 'code' => 'DK', 'quality' => 1.1, 'hubs' => ['HKG']],
['name' => 'DL - Delta Air Lines', 'code' => 'DL', 'quality' => 1.30, 'hubs' => ['ATL', 'DTW', 'MSP', 'SLC', 'LAX', 'JFK']],
['name' => 'DM - Maersk Air', 'code' => 'DM', 'quality' => 1.35, 'hubs' => ['GRU']],
['name' => 'DN - VASO', 'code' => 'DN', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => 'DO - Air Vallee', 'code' => 'DO', 'quality' => 1, 'hubs' => ['SIN']],
['name' => 'DP - First Choice Airways', 'code' => 'DP', 'quality' => 1.3, 'hubs' => ['ADD']],
['name' => 'DQ - Star Air', 'code' => 'DQ', 'quality' => 1.05, 'hubs' => ['JNB']],
['name' => 'DR - Air Mediterranee', 'code' => 'DR', 'quality' => 1.05, 'hubs' => ['MAD']],
['name' => 'DS - Easyjet Switzerland', 'code' => 'DS', 'quality' => 1.35, 'hubs' => ['NAN']],
['name' => 'DT - TAAG Angola Airlines', 'code' => 'DT', 'quality' => 1.25, 'hubs' => ['MXP']],
['name' => 'DU - ROLAND AIR', 'code' => 'DU', 'quality' => 1, 'hubs' => ['TLV']],
['name' => 'DV - SCAT Airlines', 'code' => 'DV', 'quality' => 1.25, 'hubs' => ['NAN']],
['name' => 'DW - AERO-CHARTER UKRAINE', 'code' => 'DW', 'quality' => 1.25, 'hubs' => ['LAX']],
['name' => 'DX - Danish Air Transport', 'code' => 'DX', 'quality' => 1.3, 'hubs' => ['LAG']],
['name' => 'DY - Norwegian Air Shuttle', 'code' => 'DY', 'quality' => 1.05, 'hubs' => ['SCL']],
['name' => 'E0 - TAES', 'code' => 'E0', 'quality' => 1.05, 'hubs' => ['MEX']],
['name' => 'E2 - RIO GRANDE AIR', 'code' => 'E2', 'quality' => 1.25, 'hubs' => ['VIE']],
['name' => 'E3 - Domodedovo Airlines', 'code' => 'E3', 'quality' => 1.25, 'hubs' => ['AUH']],
['name' => 'E4 - Aero Asia International', 'code' => 'E4', 'quality' => 1.35, 'hubs' => ['CAI']],
['name' => 'E5 - Samara Airlines', 'code' => 'E5', 'quality' => 1.25, 'hubs' => ['AMS']],
['name' => 'E6 - Aviaexpresscruise (Russia)', 'code' => 'E6', 'quality' => 1.3, 'hubs' => ['LIM']],
['name' => 'E7 - EUROPEAN AVIATION AIR CHARTER', 'code' => 'E7', 'quality' => 1.3, 'hubs' => ['CMN']],
['name' => 'E8 - Alpi Eagles', 'code' => 'E8', 'quality' => 1.05, 'hubs' => ['NBO']],
['name' => 'E9 - Evelop Airlines', 'code' => 'E9', 'quality' => 1.3, 'hubs' => ['HND']],
['name' => 'EA - Philippine Eagle Airlines', 'code' => 'EA', 'quality' => 1.35, 'hubs' => ['KUL']],
['name' => 'EB - Wamos Air', 'code' => 'EB', 'quality' => 1, 'hubs' => ['MAD']],
['name' => 'EC - Avialeasing', 'code' => 'EC', 'quality' => 1.3, 'hubs' => ['EZE']],
['name' => 'EE - AERO AIRLINES', 'code' => 'EE', 'quality' => 1.1, 'hubs' => ['HNL']],
['name' => 'EF - Far Eastern Air Transport', 'code' => 'EF', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'EG - Japan Asia Airways', 'code' => 'EG', 'quality' => 1.25, 'hubs' => ['MXP']],
['name' => 'EH - AIR NIPPON NETWORK', 'code' => 'EH', 'quality' => 1.1, 'hubs' => ['DOH']],
['name' => 'EI - Aer Lingus', 'code' => 'EI', 'quality' => 1, 'hubs' => ['BCN']],
['name' => 'EJ - New England Airlines', 'code' => 'EJ', 'quality' => 1.35, 'hubs' => ['MEL']],
['name' => 'EK - Emirates', 'code' => 'EK', 'quality' => 1.35, 'hubs' => ['DXB']],
['name' => 'EL - ELECTRA AIRLINES', 'code' => 'EL', 'quality' => 1, 'hubs' => ['AUH']],
['name' => 'EM - AERO BENIN', 'code' => 'EM', 'quality' => 1.05, 'hubs' => ['ZUR']],
['name' => 'EN - Air Dolomiti', 'code' => 'EN', 'quality' => 1.1, 'hubs' => ['ATL']],
['name' => 'EO - Pegas Fly', 'code' => 'EO', 'quality' => 1.05, 'hubs' => ['LAX']],
['name' => 'EP - Iran Aseman Airlines', 'code' => 'EP', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'EQ - TAME Linea Aerea del ', 'code' => 'EQ', 'quality' => 1.25, 'hubs' => ['SYD']],
['name' => 'ER - Astar Air Cargo', 'code' => 'ER', 'quality' => 1.35, 'hubs' => ['FRA']],
['name' => 'ES - DHL Aviation', 'code' => 'ES', 'quality' => 1, 'hubs' => ['HND']],
['name' => 'ET - Ethiopian Airlines', 'code' => 'ET', 'quality' => 1.10, 'hubs' => ['ADD']],
['name' => 'EU - Ecuatoriana', 'code' => 'EU', 'quality' => 1.3, 'hubs' => ['BOG']],
['name' => 'EV - Asia Service Airlines', 'code' => 'EV', 'quality' => 1.05, 'hubs' => ['AKL']],
['name' => 'EW - EUROWINGS', 'code' => 'EW', 'quality' => 1, 'hubs' => ['YYZ']],
['name' => 'EX - Aerolineas Santo Domingo', 'code' => 'EX', 'quality' => 1, 'hubs' => ['NRT']],
['name' => 'EY - Etihad Airways', 'code' => 'EY', 'quality' => 1.35, 'hubs' => ['BKK']],
['name' => 'EZ - SUN-AIR OF SCANDINAVIA', 'code' => 'EZ', 'quality' => 1.05, 'hubs' => ['HNL']],
['name' => 'F2 - Falcon Air Express', 'code' => 'F2', 'quality' => 1, 'hubs' => ['MEL']],
['name' => 'F3 - Imperial Air Charter', 'code' => 'F3', 'quality' => 1.3, 'hubs' => ['SYD']],
['name' => 'F4 - Eureca', 'code' => 'F4', 'quality' => 1.1, 'hubs' => ['LAG']],
['name' => 'F5 - COSMIC AIR', 'code' => 'F5', 'quality' => 1.25, 'hubs' => ['SYD']],
['name' => 'F6 - FIRST CAMBODIA AIRLINES', 'code' => 'F6', 'quality' => 1.3, 'hubs' => ['FCO']],
['name' => 'F7 - KAIKEN LINEAS AEREAS', 'code' => 'F7', 'quality' => 1.25, 'hubs' => ['UIO']],
['name' => 'F8 - AGENCE D\'AFFRETEMENT AERIEN INC.', 'code' => 'F8', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => 'F9 - Frontier Airlines', 'code' => 'F9', 'quality' => 1.05, 'hubs' => ['DEN', 'LAS']],
['name' => 'FA - Safair', 'code' => 'FA', 'quality' => 1.05, 'hubs' => ['EZE']],
['name' => 'FB - Bulgarian Air', 'code' => 'FB', 'quality' => 1.1, 'hubs' => ['NAN']],
['name' => 'FC - West Bird Aviation', 'code' => 'FC', 'quality' => 1.1, 'hubs' => ['LHR']],
['name' => 'FD - Cityflyer', 'code' => 'FD', 'quality' => 1.1, 'hubs' => ['BOG']],
['name' => 'FF - Tower Air', 'code' => 'FF', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => 'FG - Ariana Afghan Airlines', 'code' => 'FG', 'quality' => 1.25, 'hubs' => ['NBO']],
['name' => 'FH - Freebird Airlines', 'code' => 'FH', 'quality' => 1.3, 'hubs' => ['ICN']],
['name' => 'FI - Icelandair', 'code' => 'FI', 'quality' => 1.10, 'hubs' => ['KEF']],
['name' => 'FJ - Fiji Airways', 'code' => 'FJ', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'FL - Airtran Airways', 'code' => 'FL', 'quality' => 1.1, 'hubs' => ['BOM']],
['name' => 'FM - Shanghai Airlines', 'code' => 'FM', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => 'FN - Fastjet Airlines', 'code' => 'FN', 'quality' => 1.35, 'hubs' => ['LIM']],
['name' => 'FP - TAG AVIATION S.A.', 'code' => 'FP', 'quality' => 1.35, 'hubs' => ['ATL']],
['name' => 'FQ - Air Aruba', 'code' => 'FQ', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'FR - Ryanair', 'code' => 'FR', 'quality' => 1.00, 'hubs' => ['DUB', 'STN', 'BGY']],
['name' => 'FS - STAF', 'code' => 'FS', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => 'FT - FlyEgypt', 'code' => 'FT', 'quality' => 1.3, 'hubs' => ['FRA']],
['name' => 'FU - Fuzhou Airlines', 'code' => 'FU', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'FV - Rossiya Airlines', 'code' => 'FV', 'quality' => 1.3, 'hubs' => ['DFW']],
['name' => 'FW - Flandre Air International', 'code' => 'FW', 'quality' => 1.05, 'hubs' => ['MEL']],
['name' => 'FX - FedEx Express', 'code' => 'FX', 'quality' => 1.35, 'hubs' => ['LIM']],
['name' => 'FZ - Flydubai', 'code' => 'FZ', 'quality' => 1.3, 'hubs' => ['NRT']],
['name' => 'G2 - Dobrolet Airlines', 'code' => 'G2', 'quality' => 1.05, 'hubs' => ['AMS']],
['name' => 'G3 - Gol Trans', 'code' => 'G3', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => 'G4 - Allegiant Air', 'code' => 'G4', 'quality' => 1.35, 'hubs' => ['BOG']],
['name' => 'G5 - China Express Airlines', 'code' => 'G5', 'quality' => 1, 'hubs' => ['CDG']],
['name' => 'G7 - GANDALF AIRLINES', 'code' => 'G7', 'quality' => 1.05, 'hubs' => ['YYZ']],
['name' => 'G8 - Air Service Gabon', 'code' => 'G8', 'quality' => 1.05, 'hubs' => ['AKL']],
['name' => 'G9 - Air Arabia', 'code' => 'G9', 'quality' => 1.05, 'hubs' => ['SHJ']],
['name' => 'GA - Garuda Indonesia', 'code' => 'GA', 'quality' => 1.10, 'hubs' => ['CGK', 'DPS']],
['name' => 'GB - ABX AIR', 'code' => 'GB', 'quality' => 1.05, 'hubs' => ['SEA']],
['name' => 'GC - Linacongo - Lignes Nationales - Aeriennes', 'code' => 'GC', 'quality' => 1.3, 'hubs' => ['YVR']],
['name' => 'GD - AIR ALPHA GREENLAND', 'code' => 'GD', 'quality' => 1.3, 'hubs' => ['MEX']],
['name' => 'GE - TRANSASIA AIRWAYS', 'code' => 'GE', 'quality' => 1.35, 'hubs' => ['SYD']],
['name' => 'GF - Gulf Air', 'code' => 'GF', 'quality' => 1.10, 'hubs' => ['BAH']],
['name' => 'GG - Air Adriatic', 'code' => 'GG', 'quality' => 1, 'hubs' => ['LHR']],
['name' => 'GH - Ghana Airways', 'code' => 'GH', 'quality' => 1.35, 'hubs' => ['HKG']],
['name' => 'GI - ITEK AIR', 'code' => 'GI', 'quality' => 1.3, 'hubs' => ['SIN']],
['name' => 'GJ - Loong Air', 'code' => 'GJ', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'GL - AIR GREENLAND', 'code' => 'GL', 'quality' => 1.05, 'hubs' => ['CDG']],
['name' => 'GM - Germania Flug AG', 'code' => 'GM', 'quality' => 1.05, 'hubs' => ['NRT']],
['name' => 'GN - Air Gabon', 'code' => 'GN', 'quality' => 1.3, 'hubs' => ['MXP']],
['name' => 'GP - APG Airlines', 'code' => 'GP', 'quality' => 1.1, 'hubs' => ['YYZ']],
['name' => 'GQ - Big Sky Airlines', 'code' => 'GQ', 'quality' => 1.35, 'hubs' => ['JED']],
['name' => 'GR - Gemini Air Cargo', 'code' => 'GR', 'quality' => 1.3, 'hubs' => ['TLV']],
['name' => 'GS - TianJin Airlines', 'code' => 'GS', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'GT - Air Guilin', 'code' => 'GT', 'quality' => 1.35, 'hubs' => ['HKG']],
['name' => 'GU - Aviateca', 'code' => 'GU', 'quality' => 1, 'hubs' => ['LHR']],
['name' => 'GV - AERO FLIGHT', 'code' => 'GV', 'quality' => 1.3, 'hubs' => ['HNL']],
['name' => 'GW - Kuban Airlines', 'code' => 'GW', 'quality' => 1.05, 'hubs' => ['JED']],
['name' => 'GX - GX Airlines', 'code' => 'GX', 'quality' => 1.35, 'hubs' => ['YVR']],
['name' => 'GY - GUYANA AIRWAYS 2000', 'code' => 'GY', 'quality' => 1.05, 'hubs' => ['MAD']],
['name' => 'H1 - Hahn Air', 'code' => 'H1', 'quality' => 1.05, 'hubs' => ['ATL']],
['name' => 'H2 - SKY Airline', 'code' => 'H2', 'quality' => 1.35, 'hubs' => ['ORD']],
['name' => 'H5 - Magadan Airlines', 'code' => 'H5', 'quality' => 1, 'hubs' => ['TLV']],
['name' => 'H6 - HAGELAND AVIATION SERVICES', 'code' => 'H6', 'quality' => 1.05, 'hubs' => ['JNB']],
['name' => 'H7 - Eagle Aviation (Uganda)', 'code' => 'H7', 'quality' => 1.1, 'hubs' => ['BOG']],
['name' => 'H8 - Aircompany Airlines Kharkov', 'code' => 'H8', 'quality' => 1.25, 'hubs' => ['YVR']],
['name' => 'H9 - Helisul Taxi Aereo', 'code' => 'H9', 'quality' => 1.25, 'hubs' => ['MIA']],
['name' => 'HA - Hawaiian Airlines', 'code' => 'HA', 'quality' => 1.10, 'hubs' => ['HNL', 'OGG']],
['name' => 'HB - Malitas (Mali-Tinbouctou Air Service)', 'code' => 'HB', 'quality' => 1.25, 'hubs' => ['SCL']],
['name' => 'HC - AERO-TROPICS AIR SERVICES', 'code' => 'HC', 'quality' => 1.3, 'hubs' => ['SEA']],
['name' => 'HD - Hokkaido International Airlines - Air Do', 'code' => 'HD', 'quality' => 1.3, 'hubs' => ['DFW']],
['name' => 'HE - LGW - Luftfahrt Gesellschaft Walter', 'code' => 'HE', 'quality' => 1, 'hubs' => ['NAN']],
['name' => 'HF - Air Cote D\'Ivoire', 'code' => 'HF', 'quality' => 1.3, 'hubs' => ['AKL']],
['name' => 'HG - NIKI', 'code' => 'HG', 'quality' => 1.25, 'hubs' => ['SCL']],
['name' => 'HH - Islandsflug - Icebird Airline', 'code' => 'HH', 'quality' => 1.25, 'hubs' => ['BCN']],
['name' => 'HJ - Asian Express Airlines', 'code' => 'HJ', 'quality' => 1.3, 'hubs' => ['EZE']],
['name' => 'HK - FOUR STAR AVIATION', 'code' => 'HK', 'quality' => 1.35, 'hubs' => ['MNL']],
['name' => 'HM - Air Seychelles Limited', 'code' => 'HM', 'quality' => 1.35, 'hubs' => ['MEL']],
['name' => 'HO - Juneyao Airlines', 'code' => 'HO', 'quality' => 1.05, 'hubs' => ['LAS']],
['name' => 'HQ - Business Express Airlines - BEX', 'code' => 'HQ', 'quality' => 1.35, 'hubs' => ['MXP']],
['name' => 'HR - Hahn Air', 'code' => 'HR', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'HS - SVENSKA DIREKTFLYG', 'code' => 'HS', 'quality' => 1.35, 'hubs' => ['MXP']],
['name' => 'HT - Air Tchad', 'code' => 'HT', 'quality' => 1, 'hubs' => ['LAG']],
['name' => 'HU - Hainan Airlines', 'code' => 'HU', 'quality' => 1.3, 'hubs' => ['MAD']],
['name' => 'HV - Transavia Airlines', 'code' => 'HV', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => 'HW - North Wright Airways', 'code' => 'HW', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'HX - Hong Kong Airlines', 'code' => 'HX', 'quality' => 1.35, 'hubs' => ['BKK']],
['name' => 'HY - Uzbekistan Airways', 'code' => 'HY', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'HZ - Sakhalinskie Aviatrassy - SAT', 'code' => 'HZ', 'quality' => 1.05, 'hubs' => ['ZUR']],
['name' => 'IA - Iraqi Airways', 'code' => 'IA', 'quality' => 1, 'hubs' => ['NRT']],
['name' => 'IB - Iberia', 'code' => 'IB', 'quality' => 1.10, 'hubs' => ['MAD', 'BCN']],
['name' => 'IC - INDIAN AIRLINES CORPORATION', 'code' => 'IC', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => 'ID - Batik Air', 'code' => 'ID', 'quality' => 1.25, 'hubs' => ['JNB']],
['name' => 'IE - Solomon Airlines', 'code' => 'IE', 'quality' => 1.3, 'hubs' => ['LAS']],
['name' => 'IF - ISLAS AIRWAYS', 'code' => 'IF', 'quality' => 1.35, 'hubs' => ['MIA']],
['name' => 'IG - Air Italy', 'code' => 'IG', 'quality' => 1, 'hubs' => ['MNL']],
['name' => 'IH - Falcon Air', 'code' => 'IH', 'quality' => 1.3, 'hubs' => ['BOG']],
['name' => 'II - IBC AIRWAYS', 'code' => 'II', 'quality' => 1.1, 'hubs' => ['LIM']],
['name' => 'IK - Improtex - Imair', 'code' => 'IK', 'quality' => 1, 'hubs' => ['AKL']],
['name' => 'IL - Istanbul Airlines', 'code' => 'IL', 'quality' => 1.25, 'hubs' => ['HND']],
['name' => 'IM - Carib Express', 'code' => 'IM', 'quality' => 1.25, 'hubs' => ['FRA']],
['name' => 'IN - Macedonian Airlines', 'code' => 'IN', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => 'IO - INDONESIAN AIRLINES', 'code' => 'IO', 'quality' => 1.05, 'hubs' => ['DEN']],
['name' => 'IP - Atyrau Aue Joly', 'code' => 'IP', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'IQ - Qazaq Air', 'code' => 'IQ', 'quality' => 1.35, 'hubs' => ['SCL']],
['name' => 'IR - Iran Air', 'code' => 'IR', 'quality' => 1.35, 'hubs' => ['VIE']],
['name' => 'IS - Arnarflug - Eagle Air', 'code' => 'IS', 'quality' => 1.05, 'hubs' => ['CAI']],
['name' => 'IT - Kingfisher Airlines', 'code' => 'IT', 'quality' => 1.35, 'hubs' => ['LIM']],
['name' => 'IV - Fujian Airlines', 'code' => 'IV', 'quality' => 1.35, 'hubs' => ['GRU']],
['name' => 'IW - AOM French Airlines', 'code' => 'IW', 'quality' => 1.05, 'hubs' => ['RUH']],
['name' => 'IX - Flandre Air', 'code' => 'IX', 'quality' => 1.3, 'hubs' => ['MNL']],
['name' => 'IY - Yemenia - Yemen Airways', 'code' => 'IY', 'quality' => 1.3, 'hubs' => ['NAN']],
['name' => 'IZ - Arkia Israeli Airlines', 'code' => 'IZ', 'quality' => 1.3, 'hubs' => ['ZUR']],
['name' => 'J2 - AZERBAIJAN AIRLINES', 'code' => 'J2', 'quality' => 1.3, 'hubs' => ['YYZ']],
['name' => 'J3 - Northwestern Air', 'code' => 'J3', 'quality' => 1.05, 'hubs' => ['EZE']],
['name' => 'J4 - Buffalo Airways', 'code' => 'J4', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'J5 - AVIAPRIMA', 'code' => 'J5', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'J6 - AVCOM', 'code' => 'J6', 'quality' => 1.1, 'hubs' => ['YVR']],
['name' => 'J7 - CENTRE-AVIA', 'code' => 'J7', 'quality' => 1.25, 'hubs' => ['AKL']],
['name' => 'J8 - Berjaya Air', 'code' => 'J8', 'quality' => 1.3, 'hubs' => ['DXB']],
['name' => 'J9 - Jazeera Airways', 'code' => 'J9', 'quality' => 1.05, 'hubs' => ['BKK']],
['name' => 'JA - Air Bosna', 'code' => 'JA', 'quality' => 1, 'hubs' => ['NRT']],
['name' => 'JB - Helijet Airways', 'code' => 'JB', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'JC - JAL Express', 'code' => 'JC', 'quality' => 1.05, 'hubs' => ['LHR']],
['name' => 'JD - Capital Airlines', 'code' => 'JD', 'quality' => 1.3, 'hubs' => ['SIN']],
['name' => 'JE - Manx Airlines', 'code' => 'JE', 'quality' => 1.35, 'hubs' => ['EZE']],
['name' => 'JF - LAB Flying Service - Alaska Airlines Commuter', 'code' => 'JF', 'quality' => 1.05, 'hubs' => ['LAS']],
['name' => 'JG - Air Greece', 'code' => 'JG', 'quality' => 1.05, 'hubs' => ['ATL']],
['name' => 'JH - Nordeste - Linhas Aereas regionais', 'code' => 'JH', 'quality' => 1, 'hubs' => ['MAD']],
['name' => 'JI - Midway Airlines', 'code' => 'JI', 'quality' => 1.1, 'hubs' => ['ADD']],
['name' => 'JJ - Tam Linhas Aereas', 'code' => 'JJ', 'quality' => 1.3, 'hubs' => ['LAG']],
['name' => 'JK - Spanair', 'code' => 'JK', 'quality' => 1.25, 'hubs' => ['MAD']],
['name' => 'JL - Japan Airlines', 'code' => 'JL', 'quality' => 1.30, 'hubs' => ['NRT', 'HND']],
['name' => 'JM - Air Jamaica', 'code' => 'JM', 'quality' => 1.25, 'hubs' => ['SCL']],
['name' => 'JN - Excel Airways', 'code' => 'JN', 'quality' => 1.3, 'hubs' => ['EZE']],
['name' => 'JO - JALWAYS', 'code' => 'JO', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'JP - Adria Airways', 'code' => 'JP', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'JQ - Air Jamaica Express', 'code' => 'JQ', 'quality' => 1.25, 'hubs' => ['KUL']],
['name' => 'JR - Aerocalifornia', 'code' => 'JR', 'quality' => 1.1, 'hubs' => ['MNL']],
['name' => 'JS - Air Koryo', 'code' => 'JS', 'quality' => 1.05, 'hubs' => ['PHX']],
['name' => 'JT - Jaro International', 'code' => 'JT', 'quality' => 1.3, 'hubs' => ['DXB']],
['name' => 'JU - Air Serbia', 'code' => 'JU', 'quality' => 1.1, 'hubs' => ['MEX']],
['name' => 'JV - BEARSKIN LAKE AIR SERVICE', 'code' => 'JV', 'quality' => 1.3, 'hubs' => ['NAN']],
['name' => 'JW - Arrow Air', 'code' => 'JW', 'quality' => 1, 'hubs' => ['CMN']],
['name' => 'JX - Kal Aviation', 'code' => 'JX', 'quality' => 1.05, 'hubs' => ['NRT']],
['name' => 'JY - Interisland Airways', 'code' => 'JY', 'quality' => 1.1, 'hubs' => ['RUH']],
['name' => 'JZ - SKYWAYS EXPRESS', 'code' => 'JZ', 'quality' => 1.1, 'hubs' => ['MEX']],
['name' => 'K0 - Sunwing Airlines', 'code' => 'K0', 'quality' => 1, 'hubs' => ['PHX']],
['name' => 'K2 - Eurolot', 'code' => 'K2', 'quality' => 1.05, 'hubs' => ['NBO']],
['name' => 'K4 - Kalitta Air', 'code' => 'K4', 'quality' => 1.1, 'hubs' => ['JNB']],
['name' => 'K5 - Wings of Alaska', 'code' => 'K5', 'quality' => 1.05, 'hubs' => ['HND']],
['name' => 'K6 - Cambodia Angkor Air', 'code' => 'K6', 'quality' => 1, 'hubs' => ['AUH']],
['name' => 'K7 - ARIZONA EXPRESS AIRLINES', 'code' => 'K7', 'quality' => 1.3, 'hubs' => ['EZE']],
['name' => 'K8 - DUTCH CARIBBEAN EXPRESS', 'code' => 'K8', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'K9 - KRYLO AIRLINES', 'code' => 'K9', 'quality' => 1.1, 'hubs' => ['LAG']],
['name' => 'KA - Cathay Dragon', 'code' => 'KA', 'quality' => 1.1, 'hubs' => ['HNL']],
['name' => 'KB - Druk Air - Royal Bhutan Airlines', 'code' => 'KB', 'quality' => 1.05, 'hubs' => ['VIE']],
['name' => 'KC - Air Astana', 'code' => 'KC', 'quality' => 1.1, 'hubs' => ['MEX']],
['name' => 'KD - AIR ENTREPRISE', 'code' => 'KD', 'quality' => 1.35, 'hubs' => ['BOG']],
['name' => 'KE - Korean Air', 'code' => 'KE', 'quality' => 1.30, 'hubs' => ['ICN', 'PUS']],
['name' => 'KF - Bulgarian Lucky Flight', 'code' => 'KF', 'quality' => 1.1, 'hubs' => ['LIM']],
['name' => 'KG - LINEA AEREA IAACA', 'code' => 'KG', 'quality' => 1.05, 'hubs' => ['GRU']],
['name' => 'KI - ADAM SKY CONNECTION AIRLINES', 'code' => 'KI', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'KJ - British Mediterranean Airways', 'code' => 'KJ', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'KK - Atlasjet', 'code' => 'KK', 'quality' => 1.05, 'hubs' => ['NBO']],
['name' => 'KL - KLM Royal Dutch Airlines', 'code' => 'KL', 'quality' => 1.30, 'hubs' => ['AMS']],
['name' => 'KM - Air Malta', 'code' => 'KM', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => 'KO - ALASKA CENTRAL EXPRESS', 'code' => 'KO', 'quality' => 1.25, 'hubs' => ['CDG']],
['name' => 'KP - Kiwi International Air Lines', 'code' => 'KP', 'quality' => 1.1, 'hubs' => ['CAI']],
['name' => 'KQ - Kenya Airways', 'code' => 'KQ', 'quality' => 1, 'hubs' => ['MEL']],
['name' => 'KR - Kitty Hawk Air Cargo', 'code' => 'KR', 'quality' => 1.3, 'hubs' => ['SYD']],
['name' => 'KS - PENINSULA AIRWAYS', 'code' => 'KS', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => 'KT - Kampuchea Airlines', 'code' => 'KT', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'KU - Kuwait Airways', 'code' => 'KU', 'quality' => 1.05, 'hubs' => ['CGK']],
['name' => 'KV - EASTERN AIR [SOUTH AFRICA]', 'code' => 'KV', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'KW - Kelowna Flightcraft Air Charter', 'code' => 'KW', 'quality' => 1.25, 'hubs' => ['BAH']],
['name' => 'KX - Cayman Airways', 'code' => 'KX', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'KY - Kunming Airlines', 'code' => 'KY', 'quality' => 1, 'hubs' => ['CGK']],
['name' => 'KZ - NCA Nippon Cargo Airlines', 'code' => 'KZ', 'quality' => 1, 'hubs' => ['ADD']],
['name' => 'L2 - Lynden Air Cargo', 'code' => 'L2', 'quality' => 1.1, 'hubs' => ['LAS']],
['name' => 'L3 - LTU BILLA', 'code' => 'L3', 'quality' => 1.35, 'hubs' => ['NRT']],
['name' => 'L4 - Lauda Air Italy', 'code' => 'L4', 'quality' => 1.35, 'hubs' => ['AMS']],
['name' => 'L5 - Lufttransport', 'code' => 'L5', 'quality' => 1.35, 'hubs' => ['DXB']],
['name' => 'L6 - Mauritanian Airlines', 'code' => 'L6', 'quality' => 1.25, 'hubs' => ['JNB']],
['name' => 'L7 - Laoag International', 'code' => 'L7', 'quality' => 1.3, 'hubs' => ['IST']],
['name' => 'L8 - Leisure Air', 'code' => 'L8', 'quality' => 1, 'hubs' => ['BAH']],
['name' => 'L9 - Air Mali', 'code' => 'L9', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => 'LA - LAN Airlines', 'code' => 'LA', 'quality' => 1.10, 'hubs' => ['SCL', 'LIM']],
['name' => 'LB - LAB - Lloyd Aereo Boliviano', 'code' => 'LB', 'quality' => 1.3, 'hubs' => ['HND']],
['name' => 'LC - Loganair', 'code' => 'LC', 'quality' => 1.25, 'hubs' => ['ADD']],
['name' => 'LD - LINEA TURISTICA AEREOTUY', 'code' => 'LD', 'quality' => 1.1, 'hubs' => ['YVR']],
['name' => 'LF - Hinduja Cargo Services', 'code' => 'LF', 'quality' => 1, 'hubs' => ['DFW']],
['name' => 'LG - Luxair', 'code' => 'LG', 'quality' => 1.05, 'hubs' => ['MNL']],
['name' => 'LH - Lufthansa', 'code' => 'LH', 'quality' => 1.35, 'hubs' => ['FRA', 'MUC']],
['name' => 'LI - LIAT Airlines', 'code' => 'LI', 'quality' => 1.35, 'hubs' => ['CMN']],
['name' => 'LJ - Jin Air', 'code' => 'LJ', 'quality' => 1.3, 'hubs' => ['MEL']],
['name' => 'LK - Luzair', 'code' => 'LK', 'quality' => 1.25, 'hubs' => ['DXB']],
['name' => 'LL - Allegro Air', 'code' => 'LL', 'quality' => 1.25, 'hubs' => ['BKK']],
['name' => 'LM - Loganair Limited', 'code' => 'LM', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'LN - Libyan Arab Airlines', 'code' => 'LN', 'quality' => 1.35, 'hubs' => ['NRT']],
['name' => 'LO - LOT Polish Airlines', 'code' => 'LO', 'quality' => 1.10, 'hubs' => ['WAW']],
['name' => 'LP - LATAM Airlines Peru', 'code' => 'LP', 'quality' => 1, 'hubs' => ['HKG']],
['name' => 'LQ - Lebanese Air Transport', 'code' => 'LQ', 'quality' => 1.1, 'hubs' => ['LAG']],
['name' => 'LR - Avianca Costa Rica', 'code' => 'LR', 'quality' => 1, 'hubs' => ['NAN']],
['name' => 'LS - CHANNEL EXPRESS AIR SERVICES', 'code' => 'LS', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'LT - LTU International Airways', 'code' => 'LT', 'quality' => 1.1, 'hubs' => ['FCO']],
['name' => 'LU - LTU Süd', 'code' => 'LU', 'quality' => 1.3, 'hubs' => ['LHR']],
['name' => 'LV - Albanian Airlines MAK', 'code' => 'LV', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'LW - Air Nevada Airlines', 'code' => 'LW', 'quality' => 1.05, 'hubs' => ['AMS']],
['name' => 'LX - Swiss', 'code' => 'LX', 'quality' => 1.30, 'hubs' => ['ZUR']],
['name' => 'LY - El Al Israel Airlines', 'code' => 'LY', 'quality' => 1.10, 'hubs' => ['TLV']],
['name' => 'LZ - Balkan Bulgarian Airlines', 'code' => 'LZ', 'quality' => 1.05, 'hubs' => ['RUH']],
['name' => 'M2 - Mahfooz Aviation', 'code' => 'M2', 'quality' => 1.05, 'hubs' => ['LHR']],
['name' => 'M3 - LATAM Cargo Brasil', 'code' => 'M3', 'quality' => 1, 'hubs' => ['MEL']],
['name' => 'M4 - Mistral Air', 'code' => 'M4', 'quality' => 1.35, 'hubs' => ['MEX']],
['name' => 'M6 - AmeriJet International', 'code' => 'M6', 'quality' => 1.35, 'hubs' => ['VIE']],
['name' => 'M7 - MasAir', 'code' => 'M7', 'quality' => 1.05, 'hubs' => ['AUH']],
['name' => 'M8 - MCNEELY CHARTER SERVICES INC.', 'code' => 'M8', 'quality' => 1, 'hubs' => ['EZE']],
['name' => 'M9 - Motor Sich', 'code' => 'M9', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'MA - Malev Hungarian Airlines', 'code' => 'MA', 'quality' => 1.3, 'hubs' => ['MEL']],
['name' => 'MB - MNG Airlines', 'code' => 'MB', 'quality' => 1.35, 'hubs' => ['MAD']],
['name' => 'MC - Macedonian Airlines', 'code' => 'MC', 'quality' => 1.35, 'hubs' => ['ATL']],
['name' => 'MD - Air Madagascar', 'code' => 'MD', 'quality' => 1.1, 'hubs' => ['BOG']],
['name' => 'ME - Middle East Airlines', 'code' => 'ME', 'quality' => 1, 'hubs' => ['BOG']],
['name' => 'MF - XiamenAir', 'code' => 'MF', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'MG - Champion Air', 'code' => 'MG', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'MH - Malaysia Airlines', 'code' => 'MH', 'quality' => 1.10, 'hubs' => ['KUL']],
['name' => 'MI - SilkAir ', 'code' => 'MI', 'quality' => 1.3, 'hubs' => ['MEL']],
['name' => 'MJ - ARG LINEA PRIVADA ARGENTINA', 'code' => 'MJ', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'MK - Air Mauritius', 'code' => 'MK', 'quality' => 1.35, 'hubs' => ['ADD']],
['name' => 'ML - ATTICO', 'code' => 'ML', 'quality' => 1, 'hubs' => ['GRU']],
['name' => 'MM - SAM - Sociedad Aeonautica de Medellin', 'code' => 'MM', 'quality' => 1, 'hubs' => ['EZE']],
['name' => 'MN - Comair', 'code' => 'MN', 'quality' => 1.35, 'hubs' => ['LAG']],
['name' => 'MO - Calm Air', 'code' => 'MO', 'quality' => 1.25, 'hubs' => ['SIN']],
['name' => 'MP - Martinair Cargo', 'code' => 'MP', 'quality' => 1, 'hubs' => ['KUL']],
['name' => 'MQ - EXECUTIVE AIRLINES [PR-USA]', 'code' => 'MQ', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'MR - Air Mauritanie', 'code' => 'MR', 'quality' => 1.25, 'hubs' => ['SIN']],
['name' => 'MS - Egyptair', 'code' => 'MS', 'quality' => 1.10, 'hubs' => ['CAI']],
['name' => 'MT - Thomas Cook Airlines', 'code' => 'MT', 'quality' => 1.3, 'hubs' => ['AMS']],
['name' => 'MU - China Eastern Airlines', 'code' => 'MU', 'quality' => 1.30, 'hubs' => ['PVG', 'KMG']],
['name' => 'MV - ARMENIAN INTERNATIONAL AIRWAYS', 'code' => 'MV', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'MW - Maya Island Air', 'code' => 'MW', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'MX - Mexicana', 'code' => 'MX', 'quality' => 1.1, 'hubs' => ['BKK']],
['name' => 'MY - Mas Air Cargo', 'code' => 'MY', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'MZ - Merpati Nusantara Airlines', 'code' => 'MZ', 'quality' => 1.25, 'hubs' => ['JNB']],
['name' => 'N2 - Aerolineas Internacionales', 'code' => 'N2', 'quality' => 1.35, 'hubs' => ['ORD']],
['name' => 'N3 - OMSKAVIA', 'code' => 'N3', 'quality' => 1.35, 'hubs' => ['BOG']],
['name' => 'N4 - Nordwind Airlines', 'code' => 'N4', 'quality' => 1.25, 'hubs' => ['ADD']],
['name' => 'N5 - Nations Air', 'code' => 'N5', 'quality' => 1.35, 'hubs' => ['HNL']],
['name' => 'N6 - Aero Continente', 'code' => 'N6', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => 'N7 - LAGUN AIR', 'code' => 'N7', 'quality' => 1.3, 'hubs' => ['VIE']],
['name' => 'N8 - Air Pacific Crake', 'code' => 'N8', 'quality' => 1, 'hubs' => ['SIN']],
['name' => 'NA - North American Airlines', 'code' => 'NA', 'quality' => 1.25, 'hubs' => ['CDG']],
['name' => 'NB - STERLING EUROPEAN AIRLINES', 'code' => 'NB', 'quality' => 1, 'hubs' => ['LAG']],
['name' => 'NC - National Jet Systems', 'code' => 'NC', 'quality' => 1, 'hubs' => ['LAG']],
['name' => 'NE - Nesma Airlines', 'code' => 'NE', 'quality' => 1.1, 'hubs' => ['DXB']],
['name' => 'NF - Air Vanuatu', 'code' => 'NF', 'quality' => 1.35, 'hubs' => ['RUH']],
['name' => 'NG - Lauda Air', 'code' => 'NG', 'quality' => 1, 'hubs' => ['HNL']],
['name' => 'NH - All Nippon Airways', 'code' => 'NH', 'quality' => 1.30, 'hubs' => ['NRT', 'HND']],
['name' => 'NI - PGA-Portugalia Airlines', 'code' => 'NI', 'quality' => 1.35, 'hubs' => ['GRU']],
['name' => 'NJ - Vanguard Airlines', 'code' => 'NJ', 'quality' => 1.1, 'hubs' => ['DEN']],
['name' => 'NK - Spirit Airlines', 'code' => 'NK', 'quality' => 1.00, 'hubs' => ['FLL', 'LAS', 'ORD']],
['name' => 'NL - Air Liberia', 'code' => 'NL', 'quality' => 1.3, 'hubs' => ['GRU']],
['name' => 'NM - Air New Zealand Link / Mount Cook Airlines', 'code' => 'NM', 'quality' => 1.05, 'hubs' => ['BOG']],
['name' => 'NO - Neos', 'code' => 'NO', 'quality' => 1.05, 'hubs' => ['ZUR']],
['name' => 'NP - Nile Air', 'code' => 'NP', 'quality' => 1.1, 'hubs' => ['AKL']],
['name' => 'NR - RUSS AIR TRANSPORT COMPANY', 'code' => 'NR', 'quality' => 1.35, 'hubs' => ['MIA']],
['name' => 'NS - Hebei Airlines', 'code' => 'NS', 'quality' => 1.05, 'hubs' => ['CDG']],
['name' => 'NT - Binter Canarias', 'code' => 'NT', 'quality' => 1.05, 'hubs' => ['MEL']],
['name' => 'NU - Japan Transocean Air', 'code' => 'NU', 'quality' => 1.35, 'hubs' => ['DFW']],
['name' => 'NV - NORTHERN EXECUTIVE AVIATION LTD.', 'code' => 'NV', 'quality' => 1, 'hubs' => ['MEL']],
['name' => 'NW - Northwest Airlines', 'code' => 'NW', 'quality' => 1.30, 'hubs' => ['DTW', 'MSP']],
['name' => 'NX - Air Macau', 'code' => 'NX', 'quality' => 1.05, 'hubs' => ['SEA']],
['name' => 'NY - Air Iceland - Flugfelag Islands', 'code' => 'NY', 'quality' => 1.25, 'hubs' => ['CGK']],
['name' => 'NZ - Air New Zealand', 'code' => 'NZ', 'quality' => 1.10, 'hubs' => ['AKL', 'CHC']],
['name' => 'O3 - SF Airlines', 'code' => 'O3', 'quality' => 1, 'hubs' => ['SYD']],
['name' => 'O6 - Oceanair', 'code' => 'O6', 'quality' => 1.3, 'hubs' => ['CAI']],
['name' => 'OA - Olympic Airways', 'code' => 'OA', 'quality' => 1, 'hubs' => ['LAS']],
['name' => 'OB - BoA Boliviana de Aviacion', 'code' => 'OB', 'quality' => 1.35, 'hubs' => ['DEN']],
['name' => 'OC - OMNI Aviacao e Technologia', 'code' => 'OC', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'OD - Malindo Airways', 'code' => 'OD', 'quality' => 1, 'hubs' => ['DFW']],
['name' => 'OE - AIR OMEGA [GERMANY]', 'code' => 'OE', 'quality' => 1, 'hubs' => ['EZE']],
['name' => 'OF - Overland Airways', 'code' => 'OF', 'quality' => 1.35, 'hubs' => ['JNB']],
['name' => 'OG - GO Fly', 'code' => 'OG', 'quality' => 1.35, 'hubs' => ['GRU']],
['name' => 'OH - Comair/Delta Connection', 'code' => 'OH', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'OJ - OVERLAND AIRWAYS', 'code' => 'OJ', 'quality' => 1.1, 'hubs' => ['VIE']],
['name' => 'OK - Czech Airlines', 'code' => 'OK', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'OL - OLT - Ostfriesische Lufttransport', 'code' => 'OL', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'OM - MIAT Mongolian Airlines', 'code' => 'OM', 'quality' => 1.3, 'hubs' => ['SCL']],
['name' => 'ON - Air Nauru', 'code' => 'ON', 'quality' => 1.35, 'hubs' => ['MIA']],
['name' => 'OO - Skywest Airlines', 'code' => 'OO', 'quality' => 1.35, 'hubs' => ['SEA']],
['name' => 'OP - Chalk\'s International Airline', 'code' => 'OP', 'quality' => 1.1, 'hubs' => ['MIA']],
['name' => 'OR - TUI Airlines Netherlands', 'code' => 'OR', 'quality' => 1, 'hubs' => ['HNL']],
['name' => 'OS - Austrian Airlines', 'code' => 'OS', 'quality' => 1.10, 'hubs' => ['VIE']],
['name' => 'OT - AeroPelican Air Services', 'code' => 'OT', 'quality' => 1.25, 'hubs' => ['SYD']],
['name' => 'OU - Croatia Airlines', 'code' => 'OU', 'quality' => 1.1, 'hubs' => ['ATL']],
['name' => 'OV - Estonian Air', 'code' => 'OV', 'quality' => 1.05, 'hubs' => ['DEN']],
['name' => 'OW - Executive Airlines Services', 'code' => 'OW', 'quality' => 1.35, 'hubs' => ['IST']],
['name' => 'OX - Orient Thai Airlines', 'code' => 'OX', 'quality' => 1.3, 'hubs' => ['ADD']],
['name' => 'OZ - Asiana Airlines', 'code' => 'OZ', 'quality' => 1.35, 'hubs' => ['ATL']],
['name' => 'P0 - Proflight', 'code' => 'P0', 'quality' => 1, 'hubs' => ['BOG']],
['name' => 'P2 - TyumenAviaTrans', 'code' => 'P2', 'quality' => 1.25, 'hubs' => ['FCO']],
['name' => 'P3 - PHOENIX AVIATION [KYRGYZSTAN]', 'code' => 'P3', 'quality' => 1.05, 'hubs' => ['NAN']],
['name' => 'P4 - Air Peace', 'code' => 'P4', 'quality' => 1.05, 'hubs' => ['LHR']],
['name' => 'P5 - Aero Republica', 'code' => 'P5', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => 'P6 - Trans Air', 'code' => 'P6', 'quality' => 1.35, 'hubs' => ['CGK']],
['name' => 'P7 - East Line Airlines', 'code' => 'P7', 'quality' => 1.1, 'hubs' => ['CAI']],
['name' => 'P8 - Pantanal - Linhas Aereas Sul Matogrossenses', 'code' => 'P8', 'quality' => 1.05, 'hubs' => ['IST']],
['name' => 'P9 - Pro Air', 'code' => 'P9', 'quality' => 1.1, 'hubs' => ['MAD']],
['name' => 'PC - Pegasus Airlines', 'code' => 'PC', 'quality' => 1.25, 'hubs' => ['MXP']],
['name' => 'PD - Porter Airlines', 'code' => 'PD', 'quality' => 1.3, 'hubs' => ['MNL']],
['name' => 'PE - Air Europe Italy', 'code' => 'PE', 'quality' => 1.3, 'hubs' => ['PHX']],
['name' => 'PF - Palestinian Airlines', 'code' => 'PF', 'quality' => 1, 'hubs' => ['ATL']],
['name' => 'PG - Bangkok Airways', 'code' => 'PG', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'PH - Polynesian Airline of Samoa', 'code' => 'PH', 'quality' => 1.3, 'hubs' => ['SYD']],
['name' => 'PI - Sunflower Airlines', 'code' => 'PI', 'quality' => 1.1, 'hubs' => ['PHX']],
['name' => 'PJ - Air Saint Pierre', 'code' => 'PJ', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => 'PK - Pakistan International Airlines', 'code' => 'PK', 'quality' => 1.05, 'hubs' => ['KHI', 'LHE', 'ISB']],
['name' => 'PL - Delta Connection / Atlantic Southeast Airline', 'code' => 'PL', 'quality' => 1.1, 'hubs' => ['ORD']],
['name' => 'PM - Tropic Air', 'code' => 'PM', 'quality' => 1.35, 'hubs' => ['AKL']],
['name' => 'PN - Pan American Airways', 'code' => 'PN', 'quality' => 1, 'hubs' => ['BAH']],
['name' => 'PO - Polar Air Cargo', 'code' => 'PO', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'PP - Jet Aviation Business Jets - Switzerland', 'code' => 'PP', 'quality' => 1, 'hubs' => ['CDG']],
['name' => 'PR - Philippine Airlines, Inc.', 'code' => 'PR', 'quality' => 1.05, 'hubs' => ['CAI']],
['name' => 'PS - UKRAINE INTERNATIONAL', 'code' => 'PS', 'quality' => 1.3, 'hubs' => ['ICN']],
['name' => 'PT - Capital Cargo International Airlines', 'code' => 'PT', 'quality' => 1.35, 'hubs' => ['NAN']],
['name' => 'PU - PLUNA', 'code' => 'PU', 'quality' => 1.05, 'hubs' => ['MEL']],
['name' => 'PV - Air Saint Barthelemy (Barths Aviation)', 'code' => 'PV', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'PW - Precision Air', 'code' => 'PW', 'quality' => 1, 'hubs' => ['NAN']],
['name' => 'PX - Air Niugini', 'code' => 'PX', 'quality' => 1.05, 'hubs' => ['DEN']],
['name' => 'PY - Surinam Airways', 'code' => 'PY', 'quality' => 1, 'hubs' => ['AKL']],
['name' => 'PZ - LATAM Airlines Paraguay', 'code' => 'PZ', 'quality' => 1.35, 'hubs' => ['UIO']],
['name' => 'Q2 - ISLAND AVIATION SERVICES', 'code' => 'Q2', 'quality' => 1.05, 'hubs' => ['TLV']],
['name' => 'Q3 - ZAMBIAN AIRWAYS', 'code' => 'Q3', 'quality' => 1, 'hubs' => ['MEL']],
['name' => 'Q4 - Mustique Airways (Air Saint Vincent)', 'code' => 'Q4', 'quality' => 1.25, 'hubs' => ['GRU']],
['name' => 'Q5 - 40 Mile Air', 'code' => 'Q5', 'quality' => 1, 'hubs' => ['ZUR']],
['name' => 'Q6 - Aerocondor', 'code' => 'Q6', 'quality' => 1.3, 'hubs' => ['HND']],
['name' => 'Q7 - Silverjet', 'code' => 'Q7', 'quality' => 1.1, 'hubs' => ['ORD']],
['name' => 'Q8 - Trans Air Congo', 'code' => 'Q8', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'Q9 - Interbrasil Star', 'code' => 'Q9', 'quality' => 1.05, 'hubs' => ['RUH']],
['name' => 'QA - AeroCaribe', 'code' => 'QA', 'quality' => 1.25, 'hubs' => ['JFK']],
['name' => 'QB - Air Alma', 'code' => 'QB', 'quality' => 1, 'hubs' => ['NBO']],
['name' => 'QC - Camair-Co', 'code' => 'QC', 'quality' => 1.05, 'hubs' => ['SIN']],
['name' => 'QD - PEL-AIR AVIATION', 'code' => 'QD', 'quality' => 1.25, 'hubs' => ['LHR']],
['name' => 'QE - Air Moorea', 'code' => 'QE', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'QF - Qantas Airways', 'code' => 'QF', 'quality' => 1.30, 'hubs' => ['SYD', 'MEL', 'BNE']],
['name' => 'QG - Dynamic Air', 'code' => 'QG', 'quality' => 1.05, 'hubs' => ['MAD']],
['name' => 'QH - Lynton Jet - Lynton Aviation', 'code' => 'QH', 'quality' => 1.35, 'hubs' => ['DXB']],
['name' => 'QI - CIMBER AIR [DENMARK]', 'code' => 'QI', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'QJ - Latpass Airlines', 'code' => 'QJ', 'quality' => 1.3, 'hubs' => ['MIA']],
['name' => 'QK - Air Canada Jazz', 'code' => 'QK', 'quality' => 1, 'hubs' => ['LAG']],
['name' => 'QL - SERENDIB EXPRESS', 'code' => 'QL', 'quality' => 1.3, 'hubs' => ['MXP']],
['name' => 'QM - Air Malawi', 'code' => 'QM', 'quality' => 1.05, 'hubs' => ['HND']],
['name' => 'QN - Aerora', 'code' => 'QN', 'quality' => 1.3, 'hubs' => ['AKL']],
['name' => 'QO - Aeromexpress', 'code' => 'QO', 'quality' => 1.25, 'hubs' => ['DXB']],
['name' => 'QQ - ALLIANCE AIRLINES', 'code' => 'QQ', 'quality' => 1.3, 'hubs' => ['PHX']],
['name' => 'QR - Qatar Airways', 'code' => 'QR', 'quality' => 1.35, 'hubs' => ['DOH']],
['name' => 'QS - Travel Service', 'code' => 'QS', 'quality' => 1.3, 'hubs' => ['LAX']],
['name' => 'QT - TAMPA Colombia', 'code' => 'QT', 'quality' => 1.35, 'hubs' => ['JED']],
['name' => 'QU - EAST AFRICAN AIRLINES', 'code' => 'QU', 'quality' => 1.05, 'hubs' => ['EZE']],
['name' => 'QV - Lao Airlines', 'code' => 'QV', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'QW - BLUE WINGS', 'code' => 'QW', 'quality' => 1, 'hubs' => ['JNB']],
['name' => 'QX - Horizon Air/Alaska Airlines Commuter', 'code' => 'QX', 'quality' => 1.3, 'hubs' => ['HND']],
['name' => 'QY - European Air Transport', 'code' => 'QY', 'quality' => 1.3, 'hubs' => ['SYD']],
['name' => 'R2 - Orenburg Avia', 'code' => 'R2', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'R3 - Armenian Airlines', 'code' => 'R3', 'quality' => 1.25, 'hubs' => ['SYD']],
['name' => 'R4 - RUSSIA STATE TRANSPORT COMPANY', 'code' => 'R4', 'quality' => 1.25, 'hubs' => ['HKG']],
['name' => 'R5 - Jordan Aviation', 'code' => 'R5', 'quality' => 1.25, 'hubs' => ['TLV']],
['name' => 'R6 - SIMBIRSK-AERO', 'code' => 'R6', 'quality' => 1.05, 'hubs' => ['SYD']],
['name' => 'R7 - ASERCA - Aeroservicios Carabobo', 'code' => 'R7', 'quality' => 1.05, 'hubs' => ['NBO']],
['name' => 'R8 - Kyrgystan Airlines', 'code' => 'R8', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'R9 - VILLAGE AVIATION', 'code' => 'R9', 'quality' => 1.25, 'hubs' => ['BAH']],
['name' => 'RA - Nepal Airlines', 'code' => 'RA', 'quality' => 1.1, 'hubs' => ['LAX']],
['name' => 'RB - Syrianair', 'code' => 'RB', 'quality' => 1.1, 'hubs' => ['JFK']],
['name' => 'RC - Atlantic Airways', 'code' => 'RC', 'quality' => 1.1, 'hubs' => ['IST']],
['name' => 'RD - Ryan International Airlines', 'code' => 'RD', 'quality' => 1.1, 'hubs' => ['ZUR']],
['name' => 'RE - Aer Arann', 'code' => 'RE', 'quality' => 1.35, 'hubs' => ['SEA']],
['name' => 'RF - FLORIDA WEST INTERNATIONAL AIRWAYS', 'code' => 'RF', 'quality' => 1.05, 'hubs' => ['ADD']],
['name' => 'RG - Varig', 'code' => 'RG', 'quality' => 1.05, 'hubs' => ['DXB']],
['name' => 'RH - Hong Kong Air Cargo', 'code' => 'RH', 'quality' => 1, 'hubs' => ['ATL']],
['name' => 'RI - Mandala Airlines', 'code' => 'RI', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'RJ - Royal Jordanian', 'code' => 'RJ', 'quality' => 1.10, 'hubs' => ['AMM']],
['name' => 'RK - Air Afrique', 'code' => 'RK', 'quality' => 1.25, 'hubs' => ['JFK']],
['name' => 'RL - ROYAL PHNOM PENH AIRWAYS', 'code' => 'RL', 'quality' => 1.1, 'hubs' => ['MIA']],
['name' => 'RM - REGIONAL AIR [KENYA]', 'code' => 'RM', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'RN - Euralair International', 'code' => 'RN', 'quality' => 1.3, 'hubs' => ['KUL']],
['name' => 'RO - Tarom', 'code' => 'RO', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'RQ - Swiss Wings', 'code' => 'RQ', 'quality' => 1.1, 'hubs' => ['ORD']],
['name' => 'RS - Oman Royal Flight', 'code' => 'RS', 'quality' => 1.3, 'hubs' => ['SCL']],
['name' => 'RU - AirBridgeCargo Airlines', 'code' => 'RU', 'quality' => 1.05, 'hubs' => ['BCN']],
['name' => 'RV - Reeve Aleutian Airways - RAA', 'code' => 'RV', 'quality' => 1.05, 'hubs' => ['HNL']],
['name' => 'RW - US Airways Express/Chautauqua Airlines', 'code' => 'RW', 'quality' => 1.25, 'hubs' => ['ATL']],
['name' => 'RX - AVIAEXPRESS', 'code' => 'RX', 'quality' => 1.3, 'hubs' => ['RUH']],
['name' => 'RY - European Executive Express', 'code' => 'RY', 'quality' => 1.1, 'hubs' => ['AMS']],
['name' => 'RZ - SANSA', 'code' => 'RZ', 'quality' => 1.3, 'hubs' => ['AUH']],
['name' => 'S3 - Santa Barbara Airlines', 'code' => 'S3', 'quality' => 1.1, 'hubs' => ['AMS']],
['name' => 'S4 - Sata International', 'code' => 'S4', 'quality' => 1.05, 'hubs' => ['ICN']],
['name' => 'S5 - Shuttle America', 'code' => 'S5', 'quality' => 1.3, 'hubs' => ['TLV']],
['name' => 'S6 - SALMON AIR', 'code' => 'S6', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'S7 - Siberia Airlines', 'code' => 'S7', 'quality' => 1.05, 'hubs' => ['ORD']],
['name' => 'S8 - CHARLAN AIR CHARTER', 'code' => 'S8', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => 'S9 - CHS Aviation', 'code' => 'S9', 'quality' => 1.3, 'hubs' => ['FRA']],
['name' => 'SA - South African Airways', 'code' => 'SA', 'quality' => 1.10, 'hubs' => ['JNB', 'CPT']],
['name' => 'SB - Aircalin', 'code' => 'SB', 'quality' => 1.3, 'hubs' => ['CAI']],
['name' => 'SC - Shandong Airlines', 'code' => 'SC', 'quality' => 1.25, 'hubs' => ['YYZ']],
['name' => 'SD - Sudan Airways', 'code' => 'SD', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => 'SE - XL Airways', 'code' => 'SE', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'SF - Tassili Airlines', 'code' => 'SF', 'quality' => 1.3, 'hubs' => ['MEL']],
['name' => 'SG - SpiceJet', 'code' => 'SG', 'quality' => 1.05, 'hubs' => ['MNL']],
['name' => 'SI - Svea Flyg', 'code' => 'SI', 'quality' => 1, 'hubs' => ['CGK']],
['name' => 'SJ - Freedom Air', 'code' => 'SJ', 'quality' => 1.35, 'hubs' => ['CDG']],
['name' => 'SK - Scandinavian Airlines', 'code' => 'SK', 'quality' => 1.10, 'hubs' => ['ARN', 'CPH', 'OSL']],
['name' => 'SL - Thai Lion Air', 'code' => 'SL', 'quality' => 1, 'hubs' => ['DOH']],
['name' => 'SM - Air Cairo', 'code' => 'SM', 'quality' => 1.35, 'hubs' => ['BKK']],
['name' => 'SN - Brussels Airlines', 'code' => 'SN', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'SO - Superior Aviation', 'code' => 'SO', 'quality' => 1.25, 'hubs' => ['ADD']],
['name' => 'SP - SATA Air Acores', 'code' => 'SP', 'quality' => 1.35, 'hubs' => ['NRT']],
['name' => 'SQ - Singapore Airlines', 'code' => 'SQ', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => 'SR - Fly Salone', 'code' => 'SR', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'SS - Corsair International', 'code' => 'SS', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'ST - Germania', 'code' => 'ST', 'quality' => 1.3, 'hubs' => ['HKG']],
['name' => 'SU - Aeroflot', 'code' => 'SU', 'quality' => 1.10, 'hubs' => ['SVO', 'LED']],
['name' => 'SV - Saudi Airlines', 'code' => 'SV', 'quality' => 1.10, 'hubs' => ['RUH', 'JED']],
['name' => 'SW - Air Namibia', 'code' => 'SW', 'quality' => 1.05, 'hubs' => ['NRT']],
['name' => 'SX - Aeroexo - Aero Ejectivo', 'code' => 'SX', 'quality' => 1.35, 'hubs' => ['SYD']],
['name' => 'SY - Sun Country Airlines', 'code' => 'SY', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'SZ - Somon Air', 'code' => 'SZ', 'quality' => 1.1, 'hubs' => ['PHX']],
['name' => 'T0 - Avianca Peru', 'code' => 'T0', 'quality' => 1.3, 'hubs' => ['BAH']],
['name' => 'T2 - Thai Air Cargo', 'code' => 'T2', 'quality' => 1, 'hubs' => ['VIE']],
['name' => 'T3 - EASTERN AIRWAYS [UK]', 'code' => 'T3', 'quality' => 1.05, 'hubs' => ['NRT']],
['name' => 'T4 - HELLAS JET', 'code' => 'T4', 'quality' => 1.3, 'hubs' => ['MAD']],
['name' => 'T5 - Turkmenistan Airlines - Turkmenhavayollari', 'code' => 'T5', 'quality' => 1.25, 'hubs' => ['CMN']],
['name' => 'T6 - Tavrey Aircompany', 'code' => 'T6', 'quality' => 1.1, 'hubs' => ['JED']],
['name' => 'T7 - TWIN JET', 'code' => 'T7', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'T8 - TRANSPORTES AEREOS NEUQUEN', 'code' => 'T8', 'quality' => 1.1, 'hubs' => ['MEX']],
['name' => 'T9 - Transmeridian Airlines', 'code' => 'T9', 'quality' => 1.35, 'hubs' => ['NRT']],
['name' => 'TA - TACA', 'code' => 'TA', 'quality' => 1.1, 'hubs' => ['NBO']],
['name' => 'TB - US Airways Shuttle', 'code' => 'TB', 'quality' => 1.3, 'hubs' => ['SEA']],
['name' => 'TC - Air Tanzania', 'code' => 'TC', 'quality' => 1.25, 'hubs' => ['PHX']],
['name' => 'TD - Air Alsie', 'code' => 'TD', 'quality' => 1.3, 'hubs' => ['YYZ']],
['name' => 'TE - Lithuanian Airlines', 'code' => 'TE', 'quality' => 1, 'hubs' => ['BKK']],
['name' => 'TF - Braathens Regional Aviation', 'code' => 'TF', 'quality' => 1.05, 'hubs' => ['VIE']],
['name' => 'TG - Thai Airways Intl', 'code' => 'TG', 'quality' => 1.10, 'hubs' => ['BKK']],
['name' => 'TH - British Airways CitiExpress', 'code' => 'TH', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => 'TI - Tolair Services', 'code' => 'TI', 'quality' => 1.25, 'hubs' => ['ORD']],
['name' => 'TJ - TRANSPORTES AEREOS NACIONALES DE SELVA', 'code' => 'TJ', 'quality' => 1.1, 'hubs' => ['NBO']],
['name' => 'TK - Turkish Airlines', 'code' => 'TK', 'quality' => 1.30, 'hubs' => ['IST']],
['name' => 'TL - AIRNORTH REGIONAL', 'code' => 'TL', 'quality' => 1.1, 'hubs' => ['HNL']],
['name' => 'TM - LAM', 'code' => 'TM', 'quality' => 1.05, 'hubs' => ['HKG']],
['name' => 'TN - Air Tahiti Nui', 'code' => 'TN', 'quality' => 1.3, 'hubs' => ['LIM']],
['name' => 'TO - PRESIDENT AIRLINES [KAMPUCHEA]', 'code' => 'TO', 'quality' => 1.35, 'hubs' => ['PHX']],
['name' => 'TP - TAP Air Portugal', 'code' => 'TP', 'quality' => 1.10, 'hubs' => ['LIS', 'OPO']],
['name' => 'TR - Transbrasil', 'code' => 'TR', 'quality' => 1.1, 'hubs' => ['PHX']],
['name' => 'TS - Air Transat', 'code' => 'TS', 'quality' => 1.1, 'hubs' => ['DXB']],
['name' => 'TT - TCB - Transportes Charter do Brasil', 'code' => 'TT', 'quality' => 1.1, 'hubs' => ['SCL']],
['name' => 'TU - Tunisair', 'code' => 'TU', 'quality' => 1, 'hubs' => ['BOG']],
['name' => 'TV - Virgin Express', 'code' => 'TV', 'quality' => 1.25, 'hubs' => ['NRT']],
['name' => 'TW - T\'way Air', 'code' => 'TW', 'quality' => 1.1, 'hubs' => ['CAI']],
['name' => 'TX - Air Caraibes', 'code' => 'TX', 'quality' => 1.1, 'hubs' => ['DXB']],
['name' => 'TY - Air Caledonie', 'code' => 'TY', 'quality' => 1.25, 'hubs' => ['FCO']],
['name' => 'TZ - American Trans Air', 'code' => 'TZ', 'quality' => 1.05, 'hubs' => ['MIA']],
['name' => 'U2 - United Feeder Services', 'code' => 'U2', 'quality' => 1.25, 'hubs' => ['VIE']],
['name' => 'U3 - Aviaprad', 'code' => 'U3', 'quality' => 1.1, 'hubs' => ['HKG']],
['name' => 'U5 - International Business Air', 'code' => 'U5', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'U6 - Ural Airlines', 'code' => 'U6', 'quality' => 1.35, 'hubs' => ['YVR']],
['name' => 'U7 - NORTHERN DENE AIRWAYS', 'code' => 'U7', 'quality' => 1.35, 'hubs' => ['MIA']],
['name' => 'U8 - Armavia', 'code' => 'U8', 'quality' => 1.3, 'hubs' => ['SCL']],
['name' => 'U9 - TATARSTAN AIRLINES', 'code' => 'U9', 'quality' => 1.3, 'hubs' => ['LAX']],
['name' => 'UA - United Airlines', 'code' => 'UA', 'quality' => 1.30, 'hubs' => ['ORD', 'DEN', 'IAH', 'LAX', 'EWR', 'SFO']],
['name' => 'UB - Myanmar International Airways', 'code' => 'UB', 'quality' => 1.35, 'hubs' => ['LAG']],
['name' => 'UC - LATAM Cargo Chile', 'code' => 'UC', 'quality' => 1.25, 'hubs' => ['AKL']],
['name' => 'UD - Hex\'Air', 'code' => 'UD', 'quality' => 1, 'hubs' => ['AKL']],
['name' => 'UE - Trans European Airlines', 'code' => 'UE', 'quality' => 1, 'hubs' => ['TLV']],
['name' => 'UF - UKRAINIAN MEDITERRANEAN AIRLINES', 'code' => 'UF', 'quality' => 1.35, 'hubs' => ['UIO']],
['name' => 'UG - TUNINTER', 'code' => 'UG', 'quality' => 1.25, 'hubs' => ['BCN']],
['name' => 'UH - Eurasia Air', 'code' => 'UH', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'UI - EUROCYPRIA', 'code' => 'UI', 'quality' => 1.05, 'hubs' => ['BOG']],
['name' => 'UJ - AlMasria Universal Airlines', 'code' => 'UJ', 'quality' => 1.25, 'hubs' => ['LIM']],
['name' => 'UK - TATA SIA AIRLINES', 'code' => 'UK', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'UL - Srilankan Airlines', 'code' => 'UL', 'quality' => 1.1, 'hubs' => ['NRT']],
['name' => 'UM - Air Zimbabwe', 'code' => 'UM', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'UN - Transaero Airlines', 'code' => 'UN', 'quality' => 1.35, 'hubs' => ['NAN']],
['name' => 'UO - Hong Kong Express Airways', 'code' => 'UO', 'quality' => 1.3, 'hubs' => ['JNB']],
['name' => 'UP - Bahamasair', 'code' => 'UP', 'quality' => 1.25, 'hubs' => ['HNL']],
['name' => 'UQ - Urumqi Air', 'code' => 'UQ', 'quality' => 1.1, 'hubs' => ['CMN']],
['name' => 'UR - UKRAINE NATIONAL AIRLINES', 'code' => 'UR', 'quality' => 1.25, 'hubs' => ['VIE']],
['name' => 'US - US Airways', 'code' => 'US', 'quality' => 1.10, 'hubs' => ['PHX', 'CLT', 'PHL']],
['name' => 'UT - UTair', 'code' => 'UT', 'quality' => 1.1, 'hubs' => ['ZUR']],
['name' => 'UU - Air Austral', 'code' => 'UU', 'quality' => 1.35, 'hubs' => ['JED']],
['name' => 'UV - Universal Airways', 'code' => 'UV', 'quality' => 1.1, 'hubs' => ['DFW']],
['name' => 'UW - UNIVERSAL AIRLINES [GUYANA]', 'code' => 'UW', 'quality' => 1.25, 'hubs' => ['RUH']],
['name' => 'UX - Air Europa', 'code' => 'UX', 'quality' => 1.25, 'hubs' => ['HNL']],
['name' => 'UY - Cameroon Airlines', 'code' => 'UY', 'quality' => 1.1, 'hubs' => ['JFK']],
['name' => 'UZ - BURAQ AIR TRANSPORT', 'code' => 'UZ', 'quality' => 1.35, 'hubs' => ['HKG']],
['name' => 'V2 - Karat - Aviacompany Karat', 'code' => 'V2', 'quality' => 1, 'hubs' => ['SCL']],
['name' => 'V3 - Carpatair', 'code' => 'V3', 'quality' => 1.05, 'hubs' => ['YYZ']],
['name' => 'V4 - VENSECAR INTERNACIONAL', 'code' => 'V4', 'quality' => 1.05, 'hubs' => ['MEL']],
['name' => 'V5 - Vnukovo Airlines', 'code' => 'V5', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'V6 - Air Atlantique - Air Publicite', 'code' => 'V6', 'quality' => 1.05, 'hubs' => ['DEN']],
['name' => 'V7 - Volotea', 'code' => 'V7', 'quality' => 1.3, 'hubs' => ['MIA']],
['name' => 'V8 - AVIATRANS', 'code' => 'V8', 'quality' => 1.35, 'hubs' => ['KUL']],
['name' => 'V9 - Bashkirian Airlines - Bashkirskjie Avialinii', 'code' => 'V9', 'quality' => 1.35, 'hubs' => ['YYZ']],
['name' => 'VA - Virgin Australia ', 'code' => 'VA', 'quality' => 1.3, 'hubs' => ['NBO']],
['name' => 'VB - Maersk Air (UK)', 'code' => 'VB', 'quality' => 1.25, 'hubs' => ['JNB']],
['name' => 'VC - Servivensa - Empresa Servicios Avensa SA', 'code' => 'VC', 'quality' => 1.05, 'hubs' => ['CDG']],
['name' => 'VE - Avensa', 'code' => 'VE', 'quality' => 1, 'hubs' => ['BAH']],
['name' => 'VF - VALUAIR', 'code' => 'VF', 'quality' => 1.25, 'hubs' => ['ICN']],
['name' => 'VG - VLM - Vlaamse Luchtvaart Maatschappij', 'code' => 'VG', 'quality' => 1.1, 'hubs' => ['KUL']],
['name' => 'VH - AEROPOSTAL ALAS DE VENEZOLANA', 'code' => 'VH', 'quality' => 1.35, 'hubs' => ['IST']],
['name' => 'VI - VOLGA-DNEPR AIRLINES', 'code' => 'VI', 'quality' => 1.05, 'hubs' => ['JNB']],
['name' => 'VJ - Vietjet', 'code' => 'VJ', 'quality' => 1.3, 'hubs' => ['AMS']],
['name' => 'VK - Air Nigeria', 'code' => 'VK', 'quality' => 1, 'hubs' => ['MAD']],
['name' => 'VL - Medview Airline', 'code' => 'VL', 'quality' => 1.05, 'hubs' => ['BOM']],
['name' => 'VM - VIAGGIO AIR', 'code' => 'VM', 'quality' => 1.3, 'hubs' => ['ADD']],
['name' => 'VN - Vietnam Airlines', 'code' => 'VN', 'quality' => 1.3, 'hubs' => ['DFW']],
['name' => 'VO - VOTEC SERVICIOS AEREOS REGIONNAIS', 'code' => 'VO', 'quality' => 1.1, 'hubs' => ['ICN']],
['name' => 'VP - VASP', 'code' => 'VP', 'quality' => 1.05, 'hubs' => ['AKL']],
['name' => 'VQ - Impulse Airlines', 'code' => 'VQ', 'quality' => 1, 'hubs' => ['MAD']],
['name' => 'VR - TACV Cabo Verde Airlines', 'code' => 'VR', 'quality' => 1.05, 'hubs' => ['FRA']],
['name' => 'VS - Virgin Atlantic', 'code' => 'VS', 'quality' => 1.30, 'hubs' => ['LHR', 'MAN']],
['name' => 'VT - Air Tahiti', 'code' => 'VT', 'quality' => 1.3, 'hubs' => ['GRU']],
['name' => 'VV - Aerosweet Airlines', 'code' => 'VV', 'quality' => 1, 'hubs' => ['PHX']],
['name' => 'VW - AEROMAR', 'code' => 'VW', 'quality' => 1.35, 'hubs' => ['LHR']],
['name' => 'VX - ACES Colombia', 'code' => 'VX', 'quality' => 1.3, 'hubs' => ['BCN']],
['name' => 'VY - Vueling Airlines', 'code' => 'VY', 'quality' => 1.05, 'hubs' => ['BCN', 'MAD']],
['name' => 'VZ - MyTravel Airways', 'code' => 'VZ', 'quality' => 1.25, 'hubs' => ['SCL']],
['name' => 'W3 - Arik Airlines', 'code' => 'W3', 'quality' => 1.3, 'hubs' => ['BKK']],
['name' => 'W4 - Aero Services Executive', 'code' => 'W4', 'quality' => 1, 'hubs' => ['DOH']],
['name' => 'W5 - Mahan Air', 'code' => 'W5', 'quality' => 1.1, 'hubs' => ['ADD']],
['name' => 'W6 - WIZZ AIR HUNGARY', 'code' => 'W6', 'quality' => 1.00, 'hubs' => ['BUD', 'LTN']],
['name' => 'W7 - Sayakhat', 'code' => 'W7', 'quality' => 1.35, 'hubs' => ['BOG']],
['name' => 'W8 - Cargojet Airways', 'code' => 'W8', 'quality' => 1.25, 'hubs' => ['CMN']],
['name' => 'W9 - Eastwind Airlines - The Bee Line', 'code' => 'W9', 'quality' => 1.25, 'hubs' => ['AKL']],
['name' => 'WA - KLM Cityhopper', 'code' => 'WA', 'quality' => 1.35, 'hubs' => ['JNB']],
['name' => 'WB - RwandAir', 'code' => 'WB', 'quality' => 1.25, 'hubs' => ['LAX']],
['name' => 'WC - Islena Airlines - Islena de Inversiones', 'code' => 'WC', 'quality' => 1.35, 'hubs' => ['SIN']],
['name' => 'WD - DAIRO AIR SERVICES', 'code' => 'WD', 'quality' => 1.05, 'hubs' => ['JNB']],
['name' => 'WE - Thai Smile', 'code' => 'WE', 'quality' => 1, 'hubs' => ['LIM']],
['name' => 'WF - Wideroe', 'code' => 'WF', 'quality' => 1.35, 'hubs' => ['ORD']],
['name' => 'WG - Wasaya Airways', 'code' => 'WG', 'quality' => 1.3, 'hubs' => ['NAN']],
['name' => 'WH - WDL Aviation', 'code' => 'WH', 'quality' => 1.1, 'hubs' => ['CDG']],
['name' => 'WI - White coloured by you', 'code' => 'WI', 'quality' => 1.05, 'hubs' => ['RUH']],
['name' => 'WJ - Air Labrador - Labrador Airways', 'code' => 'WJ', 'quality' => 1, 'hubs' => ['ICN']],
['name' => 'WK - Edelweiss Air', 'code' => 'WK', 'quality' => 1, 'hubs' => ['RUH']],
['name' => 'WL - World Air Network', 'code' => 'WL', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'WM - WINDWARD ISLANDS AIRWAYS INTERNATIONAL', 'code' => 'WM', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'WN - Southwest Airlines', 'code' => 'WN', 'quality' => 1.05, 'hubs' => ['DAL', 'MDW', 'LAS', 'PHX']],
['name' => 'WO - World Airways', 'code' => 'WO', 'quality' => 1.1, 'hubs' => ['NRT']],
['name' => 'WP - Aloha Island Air', 'code' => 'WP', 'quality' => 1.35, 'hubs' => ['CGK']],
['name' => 'WQ - Romavia', 'code' => 'WQ', 'quality' => 1.05, 'hubs' => ['ATL']],
['name' => 'WR - Royal Tongan Airlines', 'code' => 'WR', 'quality' => 1.25, 'hubs' => ['AKL']],
['name' => 'WS - WestJet', 'code' => 'WS', 'quality' => 1.05, 'hubs' => ['YYC', 'YYZ']],
['name' => 'WT - Nigeria Airways', 'code' => 'WT', 'quality' => 1.05, 'hubs' => ['KUL']],
['name' => 'WU - TIKAL JETS AIRLINES', 'code' => 'WU', 'quality' => 1.05, 'hubs' => ['JED']],
['name' => 'WV - SWE FLY', 'code' => 'WV', 'quality' => 1.05, 'hubs' => ['MAD']],
['name' => 'WW - Canair', 'code' => 'WW', 'quality' => 1.05, 'hubs' => ['PHX']],
['name' => 'WX - CityJet', 'code' => 'WX', 'quality' => 1.05, 'hubs' => ['LIM']],
['name' => 'WY - Oman Air', 'code' => 'WY', 'quality' => 1.1, 'hubs' => ['BOG']],
['name' => 'X3 - TUIfly', 'code' => 'X3', 'quality' => 1.25, 'hubs' => ['BKK']],
['name' => 'X5 - Cronus Airlines', 'code' => 'X5', 'quality' => 1.3, 'hubs' => ['SCL']],
['name' => 'X7 - Chitaavia', 'code' => 'X7', 'quality' => 1.3, 'hubs' => ['MXP']],
['name' => 'X8 - Aerovias DAP', 'code' => 'X8', 'quality' => 1.25, 'hubs' => ['CDG']],
['name' => 'X9 - Khors Air', 'code' => 'X9', 'quality' => 1, 'hubs' => ['GRU']],
['name' => 'XC - Corendon Airlines', 'code' => 'XC', 'quality' => 1.35, 'hubs' => ['FRA']],
['name' => 'XE - Expressjet Airlines', 'code' => 'XE', 'quality' => 1.1, 'hubs' => ['LAX']],
['name' => 'XF - Vladivostok Air', 'code' => 'XF', 'quality' => 1.35, 'hubs' => ['MEL']],
['name' => 'XH - Skyjet', 'code' => 'XH', 'quality' => 1.1, 'hubs' => ['EZE']],
['name' => 'XJ - Northwest Airlink/Mesaba Airlines', 'code' => 'XJ', 'quality' => 1.05, 'hubs' => ['IST']],
['name' => 'XK - Air Corsica', 'code' => 'XK', 'quality' => 1.1, 'hubs' => ['SCL']],
['name' => 'XL - LATAM Airlines Ecuador', 'code' => 'XL', 'quality' => 1.05, 'hubs' => ['MIA']],
['name' => 'XM - Australian Air Express', 'code' => 'XM', 'quality' => 1.35, 'hubs' => ['KUL']],
['name' => 'XO - China Xinjiang Airlines', 'code' => 'XO', 'quality' => 1.1, 'hubs' => ['LHR']],
['name' => 'XP - Casino Express', 'code' => 'XP', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => 'XQ - SunExpress', 'code' => 'XQ', 'quality' => 1, 'hubs' => ['BAH']],
['name' => 'XT - KLM Exel', 'code' => 'XT', 'quality' => 1.35, 'hubs' => ['MEL']],
['name' => 'XU - AFRICAN EXPRESS AIRWAYS', 'code' => 'XU', 'quality' => 1, 'hubs' => ['CDG']],
['name' => 'XV - WALTAIR', 'code' => 'XV', 'quality' => 1.35, 'hubs' => ['EZE']],
['name' => 'XW - China Xinhua Airlines', 'code' => 'XW', 'quality' => 1.05, 'hubs' => ['HKG']],
['name' => 'XZ - South African Express Airways', 'code' => 'XZ', 'quality' => 1, 'hubs' => ['SYD']],
['name' => 'Y2 - ALLIANCE AIR EXPRESS', 'code' => 'Y2', 'quality' => 1.05, 'hubs' => ['LHR']],
['name' => 'Y4 - Volaris', 'code' => 'Y4', 'quality' => 1.25, 'hubs' => ['BKK']],
['name' => 'Y7 - NordStar', 'code' => 'Y7', 'quality' => 1, 'hubs' => ['JNB']],
['name' => 'Y8 - Suparna Airlines', 'code' => 'Y8', 'quality' => 1.25, 'hubs' => ['NBO']],
['name' => 'Y9 - Kish Air', 'code' => 'Y9', 'quality' => 1.25, 'hubs' => ['JED']],
['name' => 'YB - South African Express Airways', 'code' => 'YB', 'quality' => 1.35, 'hubs' => ['DXB']],
['name' => 'YC - Flight West Airlines', 'code' => 'YC', 'quality' => 1.3, 'hubs' => ['LAS']],
['name' => 'YD - Gomelavia', 'code' => 'YD', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'YG - SOUTH AIRLINES', 'code' => 'YG', 'quality' => 1, 'hubs' => ['RUH']],
['name' => 'YH - West Caribbean Airways', 'code' => 'YH', 'quality' => 1.3, 'hubs' => ['YYZ']],
['name' => 'YI - Air Sunshine', 'code' => 'YI', 'quality' => 1.35, 'hubs' => ['CAI']],
['name' => 'YK - Kibris Turkish Airlines - KTHY', 'code' => 'YK', 'quality' => 1.1, 'hubs' => ['CAI']],
['name' => 'YL - EXECUTIVE AIRLINES [NY-USA]', 'code' => 'YL', 'quality' => 1.25, 'hubs' => ['YYZ']],
['name' => 'YM - Montenegro Airlines', 'code' => 'YM', 'quality' => 1.1, 'hubs' => ['HND']],
['name' => 'YN - Air Creebec', 'code' => 'YN', 'quality' => 1.05, 'hubs' => ['GRU']],
['name' => 'YP - Aero Lloyd', 'code' => 'YP', 'quality' => 1.3, 'hubs' => ['DEN']],
['name' => 'YR - SCENIC AIRLINES', 'code' => 'YR', 'quality' => 1, 'hubs' => ['CAI']],
['name' => 'YS - REGIONAL, COMPAGNIE AERIENNE EUROPEENNE', 'code' => 'YS', 'quality' => 1.05, 'hubs' => ['MEX']],
['name' => 'YT - AIR TOGO', 'code' => 'YT', 'quality' => 1.05, 'hubs' => ['LAS']],
['name' => 'YU - EuroAtlantic Airways', 'code' => 'YU', 'quality' => 1, 'hubs' => ['PHX']],
['name' => 'YV - Mesa Airlines', 'code' => 'YV', 'quality' => 1.35, 'hubs' => ['AKL']],
['name' => 'YW - Air Nostrum', 'code' => 'YW', 'quality' => 1.25, 'hubs' => ['CDG']],
['name' => 'YX - Midwest Express Airlines', 'code' => 'YX', 'quality' => 1.3, 'hubs' => ['CGK']],
['name' => 'Z2 - STYRIAN AIRWAYS', 'code' => 'Z2', 'quality' => 1.25, 'hubs' => ['MEX']],
['name' => 'Z4 - Zoom Airlines', 'code' => 'Z4', 'quality' => 1.25, 'hubs' => ['ATL']],
['name' => 'Z6 - Dnieproavia Aviation Company', 'code' => 'Z6', 'quality' => 1.05, 'hubs' => ['ICN']],
['name' => 'Z7 - ADC Airlines', 'code' => 'Z7', 'quality' => 1, 'hubs' => ['LAS']],
['name' => 'Z8 - DHL de Guatemala', 'code' => 'Z8', 'quality' => 1.25, 'hubs' => ['SEA']],
['name' => 'Z9 - Aero Zambia', 'code' => 'Z9', 'quality' => 1.05, 'hubs' => ['ADD']],
['name' => 'ZA - ASTAIR', 'code' => 'ZA', 'quality' => 1.3, 'hubs' => ['NBO']],
['name' => 'ZB - Monarch Airlines', 'code' => 'ZB', 'quality' => 1.35, 'hubs' => ['JFK']],
['name' => 'ZC - Swazi Airlink', 'code' => 'ZC', 'quality' => 1, 'hubs' => ['EZE']],
['name' => 'ZE - Eastar Jet', 'code' => 'ZE', 'quality' => 1, 'hubs' => ['MIA']],
['name' => 'ZF - ATLANTIC AIRLINES DE HONDURAS', 'code' => 'ZF', 'quality' => 1.25, 'hubs' => ['CMN']],
['name' => 'ZG - Air Affaires EJA France', 'code' => 'ZG', 'quality' => 1.25, 'hubs' => ['PHX']],
['name' => 'ZH - Shenzhen Airlines', 'code' => 'ZH', 'quality' => 1.05, 'hubs' => ['UIO']],
['name' => 'ZI - Aigle Azur', 'code' => 'ZI', 'quality' => 1.35, 'hubs' => ['MNL']],
['name' => 'ZK - GREAT LAKES AVIATION', 'code' => 'ZK', 'quality' => 1.05, 'hubs' => ['LAG']],
['name' => 'ZL - AUSTRALIAWIDE AIRLINES', 'code' => 'ZL', 'quality' => 1.3, 'hubs' => ['ADD']],
['name' => 'ZM - Scibe Airlift Zaire', 'code' => 'ZM', 'quality' => 1.35, 'hubs' => ['AUH']],
['name' => 'ZN - AIR BOURBON', 'code' => 'ZN', 'quality' => 1.05, 'hubs' => ['BKK']],
['name' => 'ZO - GREAT PLAINS AIRLINES', 'code' => 'ZO', 'quality' => 1.35, 'hubs' => ['NBO']],
['name' => 'ZP - SILK WAY AIRLINES', 'code' => 'ZP', 'quality' => 1.1, 'hubs' => ['ZUR']],
['name' => 'ZQ - CARIBBEAN SUN AIRLINES', 'code' => 'ZQ', 'quality' => 1.25, 'hubs' => ['BOM']],
['name' => 'ZR - Aviacion Zitotrans', 'code' => 'ZR', 'quality' => 1.35, 'hubs' => ['ICN']],
['name' => 'ZS - Azzurra Air', 'code' => 'ZS', 'quality' => 1.1, 'hubs' => ['SIN']],
['name' => 'ZT - Voronezh Avia', 'code' => 'ZT', 'quality' => 1.3, 'hubs' => ['KUL']],
['name' => 'ZU - ARCA Aerovias Colombianas', 'code' => 'ZU', 'quality' => 1.35, 'hubs' => ['GRU']],
['name' => 'ZV - US Airways Express/Air Midwest', 'code' => 'ZV', 'quality' => 1.25, 'hubs' => ['EZE']],
['name' => 'ZW - Air Wisconsin', 'code' => 'ZW', 'quality' => 1.25, 'hubs' => ['MEL']],
['name' => 'ZX - Air BC', 'code' => 'ZX', 'quality' => 1.35, 'hubs' => ['MNL']],
['name' => 'ZY - Ade Air Albania', 'code' => 'ZY', 'quality' => 1.05, 'hubs' => ['IST']],
];
?>