
<!DOCTYPE html>
<html lang="en">
<head>
	<title><?php echo $meta_title; ?></title>
	<meta charset="utf-8">
	<meta name="keywords" content="<?php echo $meta_key; ?>" />
	<meta name="description" content="<?php echo $meta_desc; ?>" />
	<meta name="author" content="<?php echo $this->web_title; ?>">
	<meta name="robots" content="index, follow" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <?php $this->load->view('common/css'); ?>
</head>
<body class="common-home res layout-1">
	<div id="wrapper" class="wrapper-fluid banners-effect-10">
        <?php
            $head_data['page'] = ''; 
            $this->load->view('common/header',$head_data); 
        ?>
        <div class="breadcrumbs mb-0">
            <div class="container">
                <div class="title-breadcrumb">Terms & Conditions</div>
                <ul class="breadcrumb-cate">
                    <li><a href="<?php echo base_url() ; ?>">Home</a></li>
                    <li><a href="javascript:void(0);"><strong>Terms & Conditions</strong></a></li>
                </ul>
            </div>
        </div>
        <div id="content">
			<div class="so-page-builder">
                <section class="section-style1 mt-20">
                    <div class="container page-builder-ltr">
                        <div class="row row-style row_a1">
                            <div class="col-xs-12 col_a1c about-text">
                                <div class="terms-service">
                                    <h4>Things You Must Do Before You Travel:</h4>
                                    <p>We recommend to all clients to go through the terms of any insurance affected to satisfy them as to the fitness of cover. The Company will be more than happy to accommodate your requested things but you might have to pay an Amendment Fee per person. And obviously these charges could vary from time to time. These fees can vary greatly and will be advised at the time changes are made....Keep it in mind that the booking conditions have it that the client is responsible for any amendment fees, late payments or cancellation charges that are charged on behalf of ever member present in their party. Sometimes what happens is that certain embassy requirements happen to change and when the person in his relevant country he or she may face some visa problems and the embassy officials might not let them enter. Therefore, we always advise our customers to check for up-to-date position in time before departure. We regret we cannot take any responsibility in this embassy visa related things if you are refused to enter to your relevant country. This is why we are telling you beforehand to get updated information a few hours before you travel. In case you might need to claim your monies then you must be required to fill our indemnity form and wait for approximately six months.</p>
                                    <h4>We Request Our Client(S) To:</h4>
                                    <p>We request our client once again to read every word of these terms and conditions and understand that we always suggest our clients to also get the insurance in order to ensure that they have more comfortable and trouble-free journey. It does not really matter if the airline suggests it or not. We always advise people to go for it because one never knows what the future holds so it’s always better to get the insurance. Also know that company would be very happy to make any change that can be done to make your travel more comfortable. We will definitely put forward your request to the relevant airline staff and would definitely charge a certain amount for it based on the number of people. But please know that the company’s role is more of an agent and where we try our best to make your journey comfortable, memorable and hassle-free, there are certain things that out of our hand and we cannot do anything about it. We always try our best to provide you with amazing holiday’s package, accommodation and stuff. Also keep it in mind that in case you go for any change or cancelling something, you are required to pay charges for it. Also understand that a phone call booking means as much to us as any other booking and it gets confirmed instantly.</p>
                                    <h4>Check-in Details:</h4>
                                    <p>It is requested to make sure that all your details that you give us should match with the ones on your travel documents and the ones on your passport. Please keep it in mind that our company always makes sure and tries its best to offer its every client with the best of everything. We try our best to provide you with amazing accommodation, car hire, holidays, stop over, travelling everything to be memorable and hassle-free so that you could have the best time. Our company and its members work tirelessly to make your journey trouble free. However it is important for you to keep it in mind that our company is more of an agent between the airline and you. So sometimes in fact most of the times what people request or want do not fall in our reach. So if something of that sort happens please keep it in mind and understand that even we have certain limits and where we do our best we cannot do things that are in control of the airline only. Also keep it in mind that all the amendments or special request s of your would have certain charges and you would be responsible to pay them.</p>
                                    <h4>What to Do In Case Of Any Special Request:</h4>
                                    <p>We assure that by booking us you would have a memorable time of your lives. We always ask our clients to read each and every word of our terms conditions and our privacy policy. In case you have any special request or demand or any a certain thing in a certain style be it anything, we would love to put forward your request to the relevant authority. However, you would have to pay a certain fee for that matter. By now you would have an idea about the kind of company we are and that how much your satisfaction matters to us. We also ask all our clients to always book insurance regardless of what the airline says. We strongly suggest this because no one knows what the future holds and what might happen so it is always good to book the insurance to be on the safe side. Remember whatever we suggest we suggest it to make your travel trouble-free and satisfactory.</p>
                                    <h4>Always Be Punctual:</h4>
                                    <p>Our terms and conditions and the privacy policy clearly state that the client or clients have to keep the travelling, transit time etc. kinds of information and stuff in mind. It states that the client has to be punctual. Moreover, one more very important thing that we tell our clients is that always in case you lose your bags or any other mishap happens, you cannot ask our company to pay you for anything. However, in case the airline refunds you something you would have the right to get that refund and give us our admission fee for processing and making it happen.</p>
                                    <h4>Read Every Word Of Terms And Conditions:</h4>
                                    <p>The client is asked to read every word of terms and conditions. In case you decide to go for any insurance or something then make sure you have read everything about its terms and conditions. If you want to make any change in your arrangements then make a special request for it and our team will see what can be done for it. In case you claim you want to claim your money from the airline then you might need to fill an indemnity form. Also, keep it in mind that it may take up to six months in processing and once it is done you might need to pay some fee to the admission office for processing it.</p>
                                    <h4>Welcome To All Our Clients:</h4>
                                    <p>We welcome all our clients with open hearts and want to make this trip inclusive. We suggest our clients tell us everything beforehand if you want to make any change in anything. If you want to get some additional favors. In case you or anyone travelling with you has any condition. For example, someone in your family might need a wheelchair when travelling etc. So anything of that sort, make you tell us beforehand so we could inform this to the authority responsible for making it works. However, keep it in mind that we are only the agent between you and the airline and that getting any of such favors or demands would obviously have a fee that you would have to pay.</p>
                                    <h4>Booking Conditions:</h4>
                                    <p>Keep it in mind that for every change you ask us to make; you would have to pay for the charges. Sometimes our clients call us to confirm their booking and then they stay anxious about the fact of whether the booking is confirmed or not. It is for everyone out there that every booking that you make on a phone call is as much legit as the one you do in writing. Keep in mind that once the payment has been made and you have got the receipt, your booking is confirmed.</p>
                                    <p>We suggest our clients to read each and every word of our terms and conditions and privacy policy so you have everything clear in your mind about how we work. If you want to make any change or need something more then what are we actually offering then please tell us beforehand. Also do not forget the fact that we would charge for any of that request as per person. Also know that any request that you make on phone call means us as much as the one you do through writing. So do not worry about that.</p>
                                    <h4>Our Message to All Our Clients:</h4>
                                    <p>We tell this to our clients again and again and writing it in our terms and conditions and privacy policy as well that our company only works as an agent between you and the airline. Although it is our top priority to make sure you have the best trip, it is your responsibility to remember that certain things are out of our reach and that we try our best to make everything smooth. We always tell our customers to go through each and everything written in our terms and conditions. We also tell our customers that before they take any insurance service or anything; make sure to read everything about it. If you have any certain request or wish about your trip then make sure you tell us about it at the time of booking. We assure you that we would do our best to make it work but we certainly do not guarantee that it will work.</p>
                                    <h4>Cheap Tickets:</h4>
                                    <p>Sometimes you can get comparatively cheap tickets as well in case the airline is offering some discounts or we are offering some discounts. So make sure you keep visiting our sites. We request our clients and potential clients again and again to ensure that they have read each and everything about our policy and terms and conditions. If you want to make any extra request then be sure to tell that at the time of booking.</p>
                                    <h4>Invoice Does Not Include Any Surcharges:</h4>
                                    <p>The mentioned price on the invoice does not include any surcharges. If you want to make your trip more comfortable and need some extra favor then tell us beforehand. While you requesting for extra things keep it in mind that it will have charges and that you would have to pay fee per person. We request our clients to read everything about the terms of insurance before they get it. Only thing that our company wants is our customers to have the best and memorable time with us.</p>
                                    <h4>Our Company Ensures That You Have The Best Time:</h4>
                                    <p>If you have any specific request then is sure to tell us at the time of the booking. We would love to make it happen since it is one top priority of our company to make you trip one best experience of your life. So always tell us at the time of booking.</p>
                                    <h4>Make Sure You Abide By All the Rules:</h4>
                                    <p>Keep this in mind that where we try our best to make your journey memorable, there are certain things that you have to abide by to. For example in case of amendments or cancellation of anything you would have to abide by the rule that is to pay the due charges for that matter. Also know that any booking made through phone call means as much to us as the one made through in person or writing. ... All amendments/cancellations will incur charges. Please note that a telephone booking confirmation is as firmly confirmed as if it were made/confirmed in writing.</p>
                                    <h4>Book Your Flight To Your Desired Country:</h4>
                                    <p>We suggest our clients to read every single word of our terms and conditions and privacy policy so you have everything clear in your mind about how we work. You can book ticket to whatever country you want. All you got to need is to read all the details given on our website and make a call to us. If you want to make any change or need something more then what are we delivering then please inform us at the time of the booking. Also, always remember the fact that we would charge for any of that request as per person. Also know that any request that you make through call is as much legit as the one you do through writing. So do not worry about that at all.</p>
                                    <h4>Have A Trip In Your Own Style:</h4>
                                    <p>If you want something in your own style or have any special request then feel free to tell us at the time of booking. We would love to pass it on to the relevant authority. However, we do not guarantee if it will work or not.</p>
                                    <h4>We Do Not Offer Refunds:</h4>
                                    <p>Keep it in mind that one the flight is booked you cannot change or cancel it. We make it clear that we do not offer any kinds of refunds so do avoid cancelling the flight and be on time. If you have any personal request regarding anything or if you need something, feel free to tell us at the Terms – E-Visa We try our best for you to have a memorable time. We certainly do not want you to face any difficulty of any sort coming from our end or yours. So where we do our best we also need you to do something for yourself that is to always call to embassy before your departure. Call the embassy and ask them if they have made any recent changes or if they have any updates to share. It is very important to do this because such things get change from time to time and we do not want you to get trapped in any such situation.</p>
                                    <h4>Always Be Empathetic With the Staff:</h4>
                                    <p>The customers are always told to read every word of terms and conditions for a reason. In case you decide to go for any insurance or something then make sure you have read everything about its terms and conditions in order to save yourself and us both from any sort of trouble. However, if you feel like you want to make any modification in your arrangements then you are required to make a special request for it during the time of booking and our team will see and try its best what can be done for it. However in case any inconvenience happens, and you ask us to claim your money on your behalf from the airline, airline then you might need to fill an indemnity form. Also, keep it in mind that it may take up to six months in processing and once it is done you might need to pay some fee to the admission office for processing it. Always remember that we try our best to make sure you have the best time during your trip but certain things are unreachable for us as well. So please always try to be empathetic and understand if things do not work your way.</p>
                                    <h4>Privacy Policy:</h4>
                                    <p>We request all our clients or potential clients to always read the terms and conditions and privacy policy of our company with thorough attention so you may save yourself and us both from any inconvenience that may occur in future. We clearly state in our terms and conditions that the client specifically the one who makes the booking is responsible to pay any amendment fee, late payments or cancellation charges that are charged on behalf of every member of your group. We say this again and again that always contact the relevant embassy and get the updated information about visa and all other related legal information so that when you reach to your destination, you do not face any sort of trouble. We warn our clients about this again and again because once you’ve reached to your destination, it is not our responsibility to accommodate you for anything and we cannot handle any such embassy related issues. So we would not be able to accommodate you to return to your previous country or anything of that sort. Therefore, we are always telling our clients to get the updated information from embassy and save you from any trouble. However, in case the airline offers full or partial refunds, you will definitely be entitled for them minus our admin which is for processing the funds. Keep it in mind that you are required to fill an indemnity form to claim to your refund and that it might take at least six months.</p>
                                    <h4>Be Sure To Read Everything about Privacy Policy:</h4>
                                    <p>It is the biggest desire of every single member of our company to make sure that each and every client of us gets to enjoy his or her trip and have the best time of their lives. We do not want any of our clients to face even the slightest of trouble. Which is why our terms and conditions are full of advices telling you things to do and ensure before you travel? Sometime what happens is that you get quite busy in your things before your travel and forget to prepare for your travel? Imagine how you would feel if you after so much of struggle travel to your favorite place and you get to know that you cannot stay there because the embassy has made some changes and brought some amendments in the law. You would feel terrible. Therefore in order to make sure that you do not face even slightest of trouble it is important for you to make a call to embassy before your departure and ask them of any updates if they have made any changes or not. By doing this you would be aware of every important thing and you will not have to face any trouble. It will save you from a big trouble and us from regret as it is not in our policy to accommodate you for anything after your arrival to your destination.</p>
                                    <h4>Our Privacy Policy:</h4>
                                    <p>Our privacy policy includes that whatever details we take from our clients stay confidential between us. We might need some credit card details or some personal details too. However everything that you share with us remains confidential and we do not share it with any third party ever.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
			</div>
		</div>
        <?php $this->load->view('common/footer'); ?>
    </div>
    <?php $this->load->view('common/js'); ?>
</body>
</html>